<?php
/* @var $this Mage_Checkout_Block_Onepage_Shipping_Method_Available */
/* @var $griShippingHelper Gri_Shipping_Helper_Data */
$griShippingHelper = Mage::helper('gri_shipping') ;
/* @var $coreHelper Mage_Core_Helper_Data */
$coreHelper = Mage::helper('core');
/* @var $_rate Mage_Sales_Model_Quote_Address_Rate */
?>
<?php /** @var $this Mage_Checkout_Block_Onepage_Shipping_Method_Available */ ?>
<div class="addresses">
    <div>
        <span class="checkout-shipping-title"><?php echo $griShippingHelper->__('Shipping Information'); ?></span>
        <?php if ($this->isCustomerLoggedIn()): ?>
            <input type="radio" class="change-address" name="address" checked="checked" value="<?php echo $griShippingHelper->__('Choose from Address Book')?>" /><label><?php echo $griShippingHelper->__('Choose from Address Book')?></label>
        <?php endif; ?>
    </div>
    <?php if ($this->isCustomerLoggedIn()): ?>
        <div class="list">
            <?php echo str_replace('id="billing-address-select"', 'id="billing-address-select-shipping_method"', $this->getAddressesHtmlSelect('billing')); ?>
        </div>
    <span class="edit">
        <a href="javascript:;" onclick="billing.editAddress($('billing-address-select-shipping_method') ? $('billing-address-select-shipping_method').value : '');">
            <?php echo $this->__('Edit'); ?>
        </a>
    </span>
    <div class="method-radio">
        <input type="radio" class="add-address" id="add-address" name="address" value="<?php echo $griShippingHelper->__('Add New Address')?>" /><label><?php echo $griShippingHelper->__('Add New Address')?></label>
        <script type="text/javascript">
            var el = 'add-address'; // Dom Id
            Event.observe(el, 'click', function () {
                if ( true == $(el).checked ) {
                    billing.editAddress('', true);
                    return false;
                }
            });
        </script>
    </div>
    <?php endif; ?>
    <div class="add-address-content">
        <?php // echo $this->getChildHtml('address.fields'); ?>
    </div>
    <?php if (!$this->isCustomerLoggedIn()): ?>
        <div class="details">
            <span class="edit">
                <a href="javascript:;" onclick="billing.editAddress($('billing-address-select-shipping_method') ? $('billing-address-select-shipping_method').value : '');">
                    <?php echo $this->__('Edit');?>
                </a>
            </span>
            <?php echo $this->getAddress()->format('html'); ?>
        </div>
    <?php endif; ?>
    <?php /*
    <div class="method-radio">
        <?php if ($this->isCustomerLoggedIn()): ?>
            <input type="radio" class="add-address" id="add-address" name="address" value="<?php echo $griShippingHelper->__('Add Shipping Address')?>" /><label><?php echo $griShippingHelper->__('Add Shipping Address')?></label>
            <script type="text/javascript">
                var el = 'add-address'; //Dom Id
                Event.observe(el, 'click', function () {
                    if ($(el).checked == true) {
                        billing.editAddress('', true);
                        return false;
                    }
                });
            </script>
        <?php endif; ?>
        <input type="radio" class="edit-address" id="edit-address" name="address" value="<?php echo $griShippingHelper->__('Edit Shipping Address')?>" /><label><?php echo $griShippingHelper->__('Edit Shipping Address')?></label>
        <script type="text/javascript">
            var ell = 'edit-address';
            Event.observe(ell, 'click', function () {
                if ($(ell).checked == true) {
                    billing.editAddress($('billing-address-select-shipping_method') ? $('billing-address-select-shipping_method').value : '');
                    return false;
                }
            });
        </script>
    </div>
    <div class="add-address-content">
        <?php //echo $this->getChildHtml('address.fields');?>
    </div>
    <div class="details">
        <?php echo $this->getAddress()->format('html'); ?>
    </div>
    <?php if(1==0): ?>
    <div class="actions <?php if (!$this->isCustomerLoggedIn()) { ?>guest-actions<?php } ?>">
        <div class="edit">
            <a href="javascript:void(0);" onclick="billing.editAddress($('billing-address-select-shipping_method') ? $('billing-address-select-shipping_method').value : '');"><?php echo $this->__('Edit Shipping Address'); ?></a>
        </div>
        <?php if ($this->isCustomerLoggedIn()) { ?>
        <div class="add">
            <a href="javascript:void(0);" onclick="billing.editAddress('', true);"><?php echo $this->__('Add Shipping Address'); ?></a>
        </div>
        <?php } ?>
    </div>
    <?php endif; ?>
    < */
    ?>
    <?php if ( 'CN' == $coreHelper->getDefaultCountry() ) { ?>
    <dl class="need-fapiao toggle">
        <dt><a href="javascript:;"><?php echo $this->__('Invoice Need?')?></a></dt>
        <dd class="no-display">
            <label for="available-fapiao"><?php echo $this->__('Invoice Title')?>:</label>
            <input name="fapiao" id="available-fapiao" type="text" value="<?php echo $this->getQuote()->getFapiao(); ?>"/>
            <input name="need_fapiao" class="toggle-status" type="hidden" value="0"/>
        </dd>
    </dl>
    <?php } ?>
</div>
<div class="carriers">
    <span class="checkout-delivery-title"><?php echo $griShippingHelper->__('Delivery Method')?></span>
    <?php $_shippingRateGroups = $this->getShippingRates(); ?>
    <?php if (!$_shippingRateGroups): ?>
    <p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
    <?php else: ?>
    <?php //$griShippingHelper->upgradeShippingMethod($_shippingRateGroups) ?>
    <dl class="sp-methods">
        <?php $shippingCodePrice = array(); ?>
        <?php $_sole = count($_shippingRateGroups) == 1; foreach ($_shippingRateGroups as $code => $_rates): ?>
<!--        <dt>--><?php //echo $this->escapeHtml($this->getCarrierName($code)) ?><!--</dt>-->
        <dd class="shipping-method-<?php echo $code; ?>">
            <ul>
                <?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
                <?php $shippingCodePrice[] = "'" . $_rate->getCode() . "':" . (float)$_rate->getPrice(); ?>
                <li>
                    <?php if ($_rate->getErrorMessage()): ?>
                    <ul class="messages">
                        <li class="error-msg">
                            <ul>
                                <li><?php echo $this->escapeHtml($_rate->getErrorMessage()) ?></li>
                            </ul>
                        </li>
                    </ul>
                    <?php else: ?>
                    <?php if ($_sole) : ?>
                        <input name="shipping_method" type="radio" class="radio" value="<?php echo $_rate->getCode() ?>"
                               id="s_method_<?php echo $_rate->getCode() ?>" checked="checked"/>
                        <?php else: ?>
                        <input name="shipping_method" type="radio" class="radio" value="<?php echo $_rate->getCode() ?>"
                               id="s_method_<?php echo $_rate->getCode() ?>"<?php if ($_rate->getCode() === $this->getAddressShippingMethod()) echo ' checked="checked"' ?>
                               class="radio"/>

                        <?php if ($_rate->getCode() === $this->getAddressShippingMethod()): ?>
                            <script type="text/javascript">
                                //<![CDATA[
                                lastPrice = <?php echo (float)$_rate->getPrice(); ?>;
                                //]]>
                            </script>
                            <?php endif; ?>

                        <?php endif; ?>
                    <label for="s_method_<?php echo $_rate->getCode() ?>"
                           class="s_method_<?php echo $_rate->getCode() ?>"><?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
                        <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                        <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                        <?php echo $_excl; ?>
                        <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                            (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                            <?php endif; ?>
                    </label>
                    <?php endif ?>
                </li>
                <?php endforeach; ?>
            </ul>
        </dd>
        <?php endforeach; ?>
    </dl>
    <?php endif; ?>
    <script type="text/javascript">
        //<![CDATA[
        <?php if (!empty($shippingCodePrice)): ?>
        var shippingCodePrice = {<?php echo implode(',', $shippingCodePrice); ?>};
        <?php endif; ?>

        $$('input[type="radio"][name="shipping_method"]').each(function (el) {
            Event.observe(el, 'click', function () {
                if (el.checked == true) {
                    var getShippingCode = el.getValue();
                    <?php if (!empty($shippingCodePrice)): ?>
                    var newPrice = shippingCodePrice[getShippingCode];
                    if (!lastPrice) {
                        lastPrice = newPrice;
                        quoteBaseGrandTotal += newPrice;
                    }
                    if (newPrice != lastPrice) {
                        quoteBaseGrandTotal += (newPrice - lastPrice);
                        lastPrice = newPrice;
                    }
                    <?php endif; ?>
                    checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
                    return false;
                }
            });
        });
        initShipping();
        //]]>
    </script>

    <div class="remarks">
        <label for="remarks"><?php echo $this->__('Remarks')?></label>
        <p><textarea name="remarks" rows="5" cols="65" id="remarks"></textarea></p>
<!--<input name="remarks" id="remarks" type="text" value="--><?php //echo $this->getQuote()->getRemarks(); ?><!--"/>-->
<!--<p class="remarks-text">--><?php //echo $this->__('If you choose not to receive shopping bag for eco-friendliness, please add a "No shopping bag" remark here.'); ?><!--</p>-->
    </div>
</div>
