<?php
/* @var $this Mage_Core_Block_Template */
/* @var $helper Gri_FlashSale_Helper_Data */
$helper = $this->helper('gri_flashsale');
$flashSale = $helper->getActiveFlashSale();
// If image or small image is not uploaded, use opponent
$flashSale->getImage() or $flashSale->setImage($flashSale->getSmallImage());
$flashSale->getSmallImage() or $flashSale->setSmallImage($flashSale->getImage());
$image = $flashSale->getImage();
$this->getUseSmallImage() and $image = $flashSale->getSmallImage();
if ($flashSale->getId()) { ?>
<div class="flash_ban_area clearer">
    <div class="banner-image">
        <a href="<?php echo $this->getUrl('flashsale'); ?>">
        <?php if ($image) { ?><img src="<?php echo $helper->getImageUrl($image) ?>" alt="<?php $flashSale->getTitle(); ?>"/><?php } else {
            echo $helper->__('Flash Sales');
        } ?>
        </a>
    </div>
    <div class="flash_sal_time"><?php echo $this->getChildHtml('flash.sale.count.down'); ?></div>
</div>
<?php } ?>
