<?php

return array(
    'Accessories' => array('name' => '配饰'),
    'Bags' => array('name' => '包包'),
    'Best Sellers' => array('name' => '畅销款'),
    'Booties' => array('name' => '短靴'),
    'Boots' => array('name' => '高筒靴'),
    'Bracelets' => array('name' => '手镯'),
    'Canvas ' => array('name' => '帆布鞋'),
    'Career' => array('name' => '通勤'),
    'Casual' => array('name' => '休闲'),
    'Chains' => array('name' => '手链'),
    'Clothing' => array('name' => '服装'),
    'Coats' => array('name' => '大衣'),
    'Dress' => array('name' => '连衣裙'),
    'Dresses' => array('name' => '连衣裙'),
    'Earring' => array('name' => '耳环'),
    'Editor\'s Picks' => array('name' => '推荐款'),
    'Editor’s Picks' => array('name' => '推荐款'),
    'Exclusives' => array('name' => '官网独家款'),
    'Flat ' => array('name' => '平底'),
    'Flat' => array('name' => '低跟/平底'),
    'Flats' => array('name' => '平底鞋'),
    'Gloves' => array('name' => '手套'),
    'High Heel' => array('name' => '高跟'),
    'Knit Tops' => array('name' => '针织开衫'),
    'Knitwear' => array('name' => '针织衫'),
    'Low Heel' => array('name' => '低跟'),
    'Mid Heel' => array('name' => '中跟'),
    'Mid Heels' => array('name' => '中跟'),
    'Necklaces' => array('name' => '项链'),
    'New Arrivals' => array('name' => '新品'),
    'Occasion' => array('name' => '晚宴'),
    'Outerwear' => array('name' => '外套'),
    'Pants' => array('name' => '裤装'),
    'Pants and Shorts' => array('name' => '裤子'),
    'Platform' => array('name' => '防水台'),
    'Platform Sandals' => array('name' => '防水台'),
    'Platforms' => array('name' => '防水台'),
    'Pre Order' => array('name' => 'VIP预售'),
    'Pre Sales' => array('name' => 'VIP先享折扣'),
    'Pumps' => array('name' => '单鞋'),
    'Rings' => array('name' => '戒指'),
    'Sandals' => array('name' => '凉鞋'),
    'Scarves' => array('name' => '围巾'),
    'Shoes' => array('name' => '鞋履'),
    'Shop' => array('name' => '购物'),
    'Shop by Look' => array('name' => '造型推荐'),
    'Shorts' => array('name' => '短裤'),
    'Skirts' => array('name' => '短裙'),
    'Slippers' => array('name' => '拖鞋'),
    'Sneakers' => array('name' => '休闲鞋'),
    'Socks' => array('name' => '袜子'),
    'Tops' => array('name' => '上装'),
    'VIP Exclusives' => array('name' => 'VIP专属'),
    'Wedge' => array('name' => '坡跟'),
    'Wedges' => array('name' => '坡跟'),
);
