<?php

return array(
    'Accessories' => array('name' => '配飾'),
    'Bags' => array('name' => '包袋'),
    'Best Sellers' => array('name' => '暢銷款'),
    'Bracelets' => array('name' => '手鐲'),
    'Canvas ' => array('name' => '帆布鞋'),
    'Cashmere' => array('name' => '羊絨'),
    'Casual' => array('name' => '休閒'),
    'Chains' => array('name' => '手鏈'),
    'Clothing' => array('name' => '服裝'),
    'Coats' => array('name' => '大衣'),
    'Earring' => array('name' => '耳環'),
    'Editor\'s Picks' => array('name' => '推薦款'),
    'Editor’s Picks' => array('name' => '推薦款'),
    'Exclusives' => array('name' => '官網獨家款'),
    'Flats' => array('name' => '平底鞋'),
    'Gloves' => array('name' => '手套'),
    'High Heel' => array('name' => '高跟'),
    'Knit Tops' => array('name' => '針織開衫'),
    'Low Heel' => array('name' => '低跟'),
    'Men' => array('name' => '男士'),
    'Mid Heel' => array('name' => '中跟'),
    'Mid Heels' => array('name' => '中跟'),
    'Necklaces' => array('name' => '項鏈'),
    'New Arrivals' => array('name' => '新品'),
    'Pants and Shorts' => array('name' => '褲子'),
    'Platform' => array('name' => '防水臺'),
    'Platform Sandals' => array('name' => '防水臺'),
    'Platforms' => array('name' => '防水臺'),
    'Pre Order' => array('name' => 'VIP預售'),
    'Pre Sales' => array('name' => 'VIP先享折扣'),
    'Shoes' => array('name' => '鞋履'),
    'Shop' => array('name' => '購物'),
    'Shop by Look' => array('name' => '造型推薦'),
    'Slippers' => array('name' => '拖鞋'),
    'Socks' => array('name' => '襪子'),
    'VIP Exclusives' => array('name' => 'VIP專屬'),
    'Wedge' => array('name' => '坡跟'),
    'Wedges' => array('name' => '坡跟'),
    'Belts' => array('name'=>'腰帶'),
    'Fragrance' => array('name'=>'香氛'),
    'Hats' => array('name'=>'帽子'),
    'Jewelry' => array('name'=>'珠寶首飾'),
    'Scarves' => array('name'=>'圍巾'),
    'Small Accessories' => array('name'=>'小配件'),
    'Sunglasses' => array('name'=>'太陽鏡'),
    'Watches' => array('name'=>'手錶'),
    'Backpacks' => array('name'=>'背包'),
    'Clutches' => array('name'=>'手拿包'),
    'Cross Body Bags' => array('name'=>'斜挎包'),
    'Shoulder Bags' => array('name'=>'單肩包'),
    'Top-Handle Bags' => array('name'=>'箱包'),
    'Tote Bags' => array('name'=> '手提包'),
    'Wristlets' => array('name'=> '小錢包'),
    'Beachwear' => array('name'=>'沙灘裝'),
    'Outerwear' => array('name'=>'外套'),
    'Dresses' => array('name'=>'連衣裙'),
    'Bottoms' => array('name'=>'下裝'),
    'Knitwear' => array('name'=>'針織服'),
    'Leather' => array('name'=>'皮衣'),
    'Shearling/Fur' => array('name'=>'皮草'),
    'Boots' => array('name'=>'長靴'),
    'Booties' => array('name'=>'短靴'),
    'Flats & Ballerinas' => array('name'=>'平底鞋'),
    'Pumps' => array('name'=>'高跟鞋'),
    'Sandals' => array('name'=>'涼鞋'),
    'Sneakers' => array('name'=>'運動鞋'),
    'Bracelets & Bangles' => array('name'=>'手鐲'),
    'Charms' => array('name' => '手鏈'),
    'Earrings' => array('name' => '耳環'),
    'Jewelry Box' => array('name' => '珠寶盒'),
    'Rings' => array('name' => '指環'),
    'Card Holders' => array('name' => '名片夾'),
    'Cosmetic Bags' => array('name' => '化妝包'),
    'iPad Cases' => array('name' => '電子產品配飾'),
    'Key Rings' => array('name' => '匙扣'),
    'Phone Cases' => array('name' => '電話配飾'),
    'Stationary' => array('name' => '文具'),
    'Wallets' => array('name' => '錢包'),
    'Blouses' => array('name' => '襯衫'),
    'Jersey' => array('name' => '運動裝'),
    'Shirts' => array('name' => '襯衫'),
    'Vests' => array('name' => '背心'),
    'Jackets' => array('name' => '夾克'),
    'Casual Dresses' => array('name' => '休閒裝'),
    'Evening Dresses' => array('name' => '晚裝'),
    'Pants' => array('name' => '長褲'),
    'Shorts' => array('name' => '短褲'),
    'Skirts' => array('name' => '半身裙'),
    'Coats & Jackets' => array('name' => '外套及夾克'),
    'Cardigans' => array('name' => '開襟衫'),
    'Sweaters' => array('name' => '毛衣'),
    'Tops' => array('name' => '上衣'),
    'Tailored' => array('name' => '定制款'),
    'Dress' => array('name' => '正式款'),
    'Sports' => array('name' => '運動款'),
    'Others' => array('name' => '其他'),
    'Career' => array('name'=>'行政款'),
    'Occasion' => array('name'=>'宴會款'),
    'Flat' => array('name' => '平底款'),
);
