<?php
 /* @var $this Gri_CatalogCustom_Block_Product_View */
 $maxSaleQty = min(5, Mage::getStoreConfig(Mage_CatalogInventory_Model_Stock_Item::XML_PATH_MAX_SALE_QTY));
?>

<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Update Tote'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if (!$_product->isGrouped()): ?>
        <label for="qty"><?php echo $this->__('Qty:') ?></label>
            <select name="qty" id="qty" value="<?php echo $this->getProductDefaultQty() * 1 ?>" class="qty">
                <?php for ($i = 1; $i <= $maxSaleQty; ++$i) { ?>
                    <option value="<?php echo $i; ?>" <?php if(($this->getProductDefaultQty() * 1) == $i) echo 'selected=selected';?>><?php echo $i; ?></option>
                <?php } ?>
            </select>
        <?php endif; ?>
        <div class="addto-btn">
            <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productUpdateToCartForm<?php echo $_product->getId();?>.submit(this)">
                <span><span><?php echo $buttonTitle ?></span></span></button>
        </div>
        <span id="ajax_loader<?php echo $_product->getId(); ?>" style="display:none;"><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>"/></span>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
