<?php
    /* @var $this Mage_Checkout_Block_Cart_Item_Renderer_Configurable|Mage_Checkout_Block_Cart_Item_Renderer */
    $_item = $this->getItem();
    $maxSaleQty = min(5, Mage::getStoreConfig(Mage_CatalogInventory_Model_Stock_Item::XML_PATH_MAX_SALE_QTY));
    $isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
    $canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
    $this->getProduct()->load(NULL);
    $color = $this->getProduct()->getColor();
    $size = $this->getProduct()->getSize();
    $_options = $this->getOptionList();
    /* @var $checkoutHelper Mage_Checkout_Helper_Data */
    $checkoutHelper = $this->helper('checkout');
    $_griCheckoutHelper = $this->helper('gri_checkoutcustom');
    /* @var $swatchHelper Magiatec_Colorswatch_Helper_Swatch */
    $swatchHelper = Mage::helper('magiatecolorswatch/swatch');
    $product = $this->getProduct();
    $swatchHelper->setCurrentProduct($product);
    if ($swatchHelper->isApplicable() && $_options) {
        foreach ($_options as $_option) {
            if (isset($_option['code']) && (substr($_option['code'], 0, 5) == 'color')) {
                $color = $_option['value'];
            }

            if (isset($_option['code']) && (substr($_option['code'], 0, 4) == 'size')) {
                $size = $_option['value'];
            }
        }
        if ($color && $options = $swatchHelper->getConfigurableOptions($product)){
            foreach ($options as $option) {
                if ($color == $option['label'] && $image = $option['main_image']) {
                    $this->getProduct()->setThumbnail($image);
                }
            }
        }
    }

    /* @var $hamperHelper Gri_Hamper_Helper_Data */
    $hamperHelper = $this->helper('hamper');
    $renderer = NULL;
    if ($isHamper = $product->getTypeId() == 'hamper') {
        $renderer = $hamperHelper->getQuoteItemRenderer($this, $_item, $product);
        $hamperMessage = $renderer->getMessage();
    }
?>
<tr class="cart-desktop">
    <td style="width:36%;" <?php if ($isHamper) { ?>rowspan="<?php echo $renderer->getRowSpan() + ($hamperMessage ? 1 : 0); ?>" <?php } ?>>
            <img class="product-image" src="<?php echo $this->getProductThumbnail()->resize(102,152); ?>" width="102" height="152" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" />
            <div class="item-description">
                <p class="brand up_c"><?php echo $this->escapeHtml($this->getProduct()->getAttributeText('brand')); ?></p>
                <p class="product-name">
                    <?php if ($this->hasProductUrl()):?>
                        <a href="<?php echo $this->getProductUrl() ?>" target="_blank"><?php echo $this->escapeHtml($this->getProductName()) ?></a>
                    <?php else: ?>
                        <?php echo $this->escapeHtml($this->getProductName()) ?>
                    <?php endif; ?>

                </p>
                <p class="product-sku f11 grey"><span><?php echo $this->__('SKU#') ?></span>
                    <?php echo is_object($this->getChildProduct()) ? $this->getChildProduct()->getSku() : $_item->getSku(); ?>
                </p>
                <?php if($color): ?>
                    <p class="product-color f11 grey"><span><?php echo $_griCheckoutHelper->__('Color') ?>:</span>&nbsp;<?php echo $color; ?></p>
                <?php endif;?>
                <?php if($size): ?>
                    <p class="product-size f11 grey"><span><?php echo $_griCheckoutHelper->__('Size') ?>:</span>&nbsp;<?php echo $size; ?></p>
                <?php endif;?>

                <?php if ($_options):?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <?php
                            if (isset($_option['code']) && (substr($_option['code'], 0, 4) == 'size')) {
                                $size = $_option['value'];
                                continue;
                            }
                            if (isset($_option['code']) && (substr($_option['code'], 0, 5) == 'color')) {
                                $color = $_option['value'];
                                continue;
                            }
                        ?>
                        <?php $_formattedOptionValue = $this->getFormatedOptionValue($_option) ?>
                        <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                        <dd<?php if (isset($_formattedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formattedOptionValue['value'] ?>
                            <?php if (isset($_formattedOptionValue['full_view'])): ?>
                                <div class="truncated_full_value">
                                    <dl class="item-options">
                                        <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                                        <dd><?php echo $_formattedOptionValue['full_view'] ?></dd>
                                    </dl>
                                </div>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
        <?php endif;?>
        <?php if ($messages = $this->getMessages()): ?>
            <?php foreach ($messages as $message): ?>
                <p class="item-msg <?php echo $message['type'] ?>">* <?php echo $this->escapeHtml($message['text']) ?></p>
            <?php endforeach; ?>
        <?php endif; ?>

        <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock): ?>
            <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif;?>
        <div class="f11 grey"><?php
            Mage::unregister('current_product');
            Mage::register('current_product', $this->getProduct());
            echo $this->getLayout()->createBlock('gri_countrygroup/product_view_shipsTo', NULL, array(
                'template' => 'catalog/product/view/ships_to.phtml',
            ))->toHtml();
            ?></div>
        <p class="edit_cart">
            <?php if ($isVisibleProduct): ?>
            <a href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo $this->__('Edit item parameters') ?>"><?php echo $this->__('Edit') ?></a>
            <?php endif ?>
        </p>
        </div>
    </td>
    <?php /*
    <td style="width:19%;">
        <?php if ($isHamper) { ?>
            <?php echo $this->getQty(); ?>
        <?php } else { ?>
        <span class="add" onclick="changeNum(this,1)" style="cursor:pointer;">+</span>
            <input name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" size="2" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        <span class="reduce" onclick="changeNum(this,-1)" style="cursor:pointer;">-</span>
        <?php } ?>
    </td>
 */ ?>
    <?php //Qty ?>
    <td class="a-center" style="width: 17%;">
        <?php ?>
        <select onchange="updateCart(this.value,<?php echo $_item->getId() ?>)" class="select qty" name="cart[<?php echo $_item->getId() ?>][qty]">
            <?php for( $i=1; $i <= $maxSaleQty ; $i++):?>
            <option <?php if($this->getQty() == $i) echo 'selected=selected'?>
                    value="<?php echo $this->getUrl('checkout/cart',array('productName' => $_item->getProduct()->getName(),'itemId' => $_item->getId(),'qty' => $i,'isAjax'=> 1,'_rnd'=> rand(100,1000))) ?>"><?php echo $i;?></option>
            <?php endfor;?>
        </select>
        <span id='ajax_loader_<?php echo $_item->getId() ?>' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>
    </td>

    <?php if ($canApplyMsrp): ?>
        <td style="width:17%;" <?php if ($this->helper('tax')->displayCartBothPrices()): ?> colspan="2"<?php endif; ?>>
            <span class="cart-price">
                <span class="cart-msrp-unit"><?php echo $this->__('See price before order confirmation.'); ?></span>
                <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                <a id="<?php echo $helpLinkId ?>" href="#" class="map-help-link"><?php echo $this->__("What's this?"); ?></a>
                <script type="text/javascript">
                    Catalog.Map.addHelpLink($('<?php echo $helpLinkId ?>'), "<?php echo $this->__("What's this?") ?>");
                </script>
            </span>
        </td>
    <?php else: ?>

        <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td style="width:17%;" >
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
                <span class="cart-price">
            <?php endif; ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php echo $checkoutHelper->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
                <?php else: ?>
                    <?php if (!($this->getProduct()->getPriceInCurrentCurrency() * 1) || $this->getProduct()->getPriceInCurrentCurrency() == $_item->getCalculationPrice()) { ?>
                    <?php echo $checkoutHelper->formatPrice($_item->getCalculationPrice()) ?>
                    <?php } else { ?>
                    <span class="old-price"><?php echo $checkoutHelper->formatPrice($this->getProduct()->getPriceInCurrentCurrency()) ?></span>
                    <span class="special-price"><?php echo $checkoutHelper->formatPrice($_item->getCalculationPrice()) ?></span>
                    <?php } ?>
                <?php endif; ?>

            </span>


            <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                <div class="cart-tax-info" id="eunit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                        <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $checkoutHelper->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </td>
        <?php endif; ?>
        <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td style="width:17%;">
            <?php $_incl = $checkoutHelper->getPriceInclTax($_item); ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <span class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
                <span class="cart-price">
            <?php endif; ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php echo $checkoutHelper->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?>
                <?php else: ?>
                    <?php echo $checkoutHelper->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
                <?php endif; ?>

            </span>
            <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                <div class="cart-tax-info" id="unit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                        <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $checkoutHelper->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?></span>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </td>
        <?php endif; ?>
    <?php endif; ?>
    <?php if (($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
    <td style="width:17%;">
        <?php $_incl = $checkoutHelper->getSubtotalInclTax($_item); ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>

            <?php if ($canApplyMsrp): ?>
                <span class="cart-msrp-subtotal">--</span>
            <?php else: ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php echo $checkoutHelper->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?>
                <?php else: ?>
                    <?php echo $checkoutHelper->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
                <?php endif; ?>
            <?php endif; ?>
        </span>


        <?php if (Mage::helper('weee')->getApplied($_item)): ?>

            <div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $checkoutHelper->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>

   <!--Subtotal-->
    <?php if (($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
        <td style="17%;">
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
                <span class="cart-price">
        <?php endif; ?>

                    <?php if ($canApplyMsrp): ?>
                        <span class="cart-msrp-subtotal">--</span>
                    <?php else: ?>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
                        <?php else: ?>
                            <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
                        <?php endif; ?>
                    <?php endif; ?>

        </span>
                <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                    <div class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
        </td>
    <?php endif; ?>
<!--Subtotal-->

    <td class="right_al" style="width:13%;">
        <?php /*
        <div id="addto-message-<?php echo $_item->getId() ?>"></div>
        <?php ($this->helper('wishlist')->isAllowInCart()); { ?>
            <?php if ($isVisibleProduct): ?>
                <p><a title="<?php echo $this->__('ADD TO WISH LIST'); ?>" href="javascript:void(0)"
                      onclick="addtoWhishlist('<?php echo $this->helper('gri_wishlist')->getMoveFromCartUrl($_item->getId()); ?>',<?php echo $_item->getId()?>)"
                      class="rig_txt cart_link_btn"><?php echo $this->__('ADD TO WISH LIST'); ?></a></p>
            <?php endif ?>
        <?php } ?>
        <span id="ajax_loader<?php echo $_item->getId(); ?>" style="display:none;"><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>"/></span> */ ?>

        <?php ($this->helper('wishlist')->isAllowInCart()); { ?>
            <?php if ($isVisibleProduct): ?>
                <p><a title="<?php echo $this->__('ADD TO WISHLIST'); ?>" href="<?php echo $this->helper('wishlist')->getMoveFromCartUrl($_item->getId()); ?>"
                      class="rig_txt cart_link_btn"><?php echo $this->__('ADD TO WISHLIST'); ?></a></p>
            <?php endif ?>
        <?php } ?>

        <p><a href="<?php echo $this->getDeleteUrl(); ?>" title="<?php echo $this->__('Remove item'); ?>" class="rig_txt cart_remove_btn"><?php echo $this->__('Remove'); ?></a></p>
        <?php if (0 && $isHamper) { ?>
        <p><a href="<?php echo $this->getConfigureUrl(); ?>" title="<?php echo $this->__('Edit item'); ?>" class="rig_txt cart_edit_btn"><?php echo $this->__('Edit'); ?></a></p>
        <?php } ?>
    </td>
</tr>

<div class="cart-mobile">
<p class="edit_cart remove_cart">
    <?php if ($isVisibleProduct): ?>
        <a class="edit" href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo $this->__('Edit item parameters') ?>"></a>
    <?php endif ?>
<a class="remove" href="<?php echo $this->getDeleteUrl(); ?>" title="<?php echo $this->__('Remove item'); ?>" class="rig_txt cart_remove_btn"></a>
    <?php if (0 && $isHamper) { ?>
<a href="<?php echo $this->getConfigureUrl(); ?>" title="<?php echo $this->__('Edit item'); ?>" class="rig_txt cart_edit_btn"><?php echo $this->__('Edit'); ?></a>
<?php } ?>
</p>
    <img class="product-image" src="<?php echo $this->getProductThumbnail()->resize(102,152); ?>" width="102" height="152" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" />
    <div class="item-description">
        <p class="brand up_c"><?php echo $this->escapeHtml($this->getProduct()->getAttributeText('brand')); ?></p>
        <p class="product-name">
            <?php if ($this->hasProductUrl()):?>
                <a href="<?php echo $this->getProductUrl() ?>" target="_blank"><?php echo $this->escapeHtml($this->getProductName()) ?></a>
            <?php else: ?>
                <?php echo $this->escapeHtml($this->getProductName()) ?>
            <?php endif; ?>

        </p>
        <?php if ($canApplyMsrp): ?>
            <span class="cart-price">
                <span class="cart-msrp-unit"><?php echo $this->__('See price before order confirmation.'); ?></span>
                <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                <a id="<?php echo $helpLinkId ?>" href="#" class="map-help-link"><?php echo $this->__("What's this?"); ?></a>
                <script type="text/javascript">
                    Catalog.Map.addHelpLink($('<?php echo $helpLinkId ?>'), "<?php echo $this->__("What's this?") ?>");
                </script>
            </span>
            </td>
        <?php else: ?>
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
                        <span class="cart-price">
            <?php endif; ?>
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php echo $checkoutHelper->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
                            <?php else: ?>
                                <?php if (!($this->getProduct()->getPriceInCurrentCurrency() * 1) || $this->getProduct()->getPriceInCurrentCurrency() == $_item->getCalculationPrice()) { ?>
                                    <?php echo $checkoutHelper->formatPrice($_item->getCalculationPrice()) ?>
                                <?php } else { ?>
                                    <span class="old-price"><?php echo $checkoutHelper->formatPrice($this->getProduct()->getPriceInCurrentCurrency()) ?></span>
                                    <span class="special-price"><?php echo $checkoutHelper->formatPrice($_item->getCalculationPrice()) ?></span>
                                <?php } ?>
                            <?php endif; ?>
                    </span>
                        <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                            <div class="cart-tax-info" id="eunit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                                    <?php endforeach; ?>
                                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                                    <?php endforeach; ?>
                                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </div>

                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                    <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $checkoutHelper->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <?php $_incl = $checkoutHelper->getPriceInclTax($_item); ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
                        <span class="cart-price">
            <?php endif; ?>

                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php echo $checkoutHelper->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?>
                            <?php else: ?>
                                <?php echo $checkoutHelper->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
                            <?php endif; ?>

            </span>
                        <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                            <div class="cart-tax-info" id="unit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                                    <?php endforeach; ?>
                                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                                    <?php endforeach; ?>
                                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </div>

                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                    <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $checkoutHelper->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?></span>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>
        <?php if (($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
                <?php $_incl = $checkoutHelper->getSubtotalInclTax($_item); ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
                    <span class="cart-price">
        <?php endif; ?>

                        <?php if ($canApplyMsrp): ?>
                            <span class="cart-msrp-subtotal">--</span>
                        <?php else: ?>
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php echo $checkoutHelper->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?>
                            <?php else: ?>
                                <?php echo $checkoutHelper->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
                            <?php endif; ?>
                        <?php endif; ?>
        </span>


                    <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                        <div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>

                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $checkoutHelper->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?></span>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
        <?php endif; ?>

        <p class="product-sku f11 grey"><span><?php echo $this->__('SKU#') ?></span> <?php echo is_object($this->getChildProduct()) ?
                $this->getChildProduct()->getSku() :
                $_item->getSku()
            ; ?>
        </p>
        <?php if($color): ?>
            <p class="product-color f11 grey"><span><?php echo $_griCheckoutHelper->__('Color') ?>:</span><?php echo $color; ?></p>
        <?php endif;?>
        <?php if($size): ?>
            <p class="product-size f11 grey"><span><?php echo $_griCheckoutHelper->__('Size') ?>:</span><?php echo $size; ?></p>
        <?php endif;?>

        <?php if ($_options):?>
            <dl class="item-options">
                <?php foreach ($_options as $_option) : ?>
                    <?php
                    if (isset($_option['code']) && (substr($_option['code'], 0, 4) == 'size')) {
                        $size = $_option['value'];
                        continue;
                    }
                    if (isset($_option['code']) && (substr($_option['code'], 0, 5) == 'color')) {
                        $color = $_option['value'];
                        continue;
                    }
                    ?>
                    <?php $_formattedOptionValue = $this->getFormatedOptionValue($_option) ?>
                    <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                    <dd<?php if (isset($_formattedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formattedOptionValue['value'] ?>
                        <?php if (isset($_formattedOptionValue['full_view'])): ?>
                            <div class="truncated_full_value">
                                <dl class="item-options">
                                    <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                                    <dd><?php echo $_formattedOptionValue['full_view'] ?></dd>
                                </dl>
                            </div>
                        <?php endif; ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif;?>
        <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock): ?>
            <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif;?>
        <div class="f11 grey"><?php
            Mage::unregister('current_product');
            Mage::register('current_product', $this->getProduct());
            echo $this->getLayout()->createBlock('gri_countrygroup/product_view_shipsTo', NULL, array(
                'template' => 'catalog/product/view/ships_to.phtml',
            ))->toHtml();
            ?></div>
    <?php if ($isHamper) { ?>
        <?php echo $this->getQty(); ?>
    <?php } else { ?>
        <input name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" size="2" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
    <?php } ?>
        <!--Subtotal-->
        <?php if (($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
        <div class="subtotal">
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
                <span class="cart-price">
                    <span class="cart-subtotal-price">Subtotal:</span>
                <?php endif; ?>
                    <?php if ($canApplyMsrp): ?>
                        <span class="cart-msrp-subtotal">--</span>
                    <?php else: ?>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
                        <?php else: ?>
                            <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
                        <?php endif; ?>
                    <?php endif; ?>
</span>
                <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                    <div class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
                <?php endif; ?>
                <!--Subtotal-->
</div>

    <div class="right_al">
        <?php ($this->helper('wishlist')->isAllowInCart()); { ?>
            <?php if ($isVisibleProduct): ?>
                <p><a title="<?php echo $this->__('ADD TO WISHLIST'); ?>" href="<?php echo $this->helper('wishlist')->getMoveFromCartUrl($_item->getId()); ?>" class="rig_txt cart_link_btn"><?php echo $this->__('ADD TO WISHLIST'); ?></a></p>
            <?php endif ?>
        <?php } ?>
    </div>
</div>

<?php
    /* @var $_childItem Mage_Sales_Model_Quote_Item */
    if ($isHamper) {
    foreach ($_item->getChildren() as $_childItem) {
        $_childProduct = $_childItem->getProduct()->load(NULL);
?>
    <tr class="sub-item <?php if ($_childItem->isDeleted()) { ?>no-display<?php }?>">
        <td>
            <?php if ($isGift = $renderer->getIsGift($_childItem)) { ?><p class="up_c hamper-gift"><?php echo $this->__('Extra Gift'); ?></p><?php } ?>
            <p class="up_c"><?php echo $this->escapeHtml($_childProduct->getAttributeText('brand')); ?></p>
            <p class="product-name">
                <?php echo $this->escapeHtml($_childItem->getName()); ?>
            </p>
            <p class="product-sku f11"><span><?php echo $this->__('SKU#') ?>:</span> <?php echo $_childItem->getSku(); ?></p>
            <?php if (!$isGift) { ?>
                <p class="product-price f11"><span><span><?php echo $this->__('Original Price'); ?>:</span> <?php echo $checkoutHelper->formatPrice($_childItem->getOriginalPrice()); ?></p>
            <?php } ?>
            <?php if ($messages = $renderer->getMessages()) { ?>
                <?php foreach ($messages as $message): ?>
                    <p class="item-msg <?php echo $message['type'] ?>">* <?php echo $this->escapeHtml($message['text']) ?></p>
                <?php endforeach; ?>
            <?php } ?>
        </td>
        <td>
            <?php echo $_childItem->getQty(); ?>
        </td>

        <?php if ($canApplyMsrp): ?>
            <td <?php if ($this->helper('tax')->displayCartBothPrices()): ?> colspan="2"<?php endif; ?>>&nbsp;</td>
        <?php else: ?>

            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <td>&nbsp;</td>
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <td>&nbsp;</td>
            <?php endif; ?>
        <?php endif; ?>
        <?php if (($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
            <td>&nbsp;</td>
        <?php endif; ?>
        <td>&nbsp;</td>
    </tr>
<?php } ?>
<?php if ($hamperMessage) { ?>
    <tr class="sub-item last-sub-item">
        <td colspan="3">
            <div class="message">
                <p class="item-msg item-msg-to"><span><?php echo $this->__('To') ?>:</span> <?php echo $this->escapeHtml($hamperMessage['to']) ?></p>
                <p class="item-msg item-msg-from"><span><?php echo $this->__('From') ?>:</span> <?php echo $this->escapeHtml($hamperMessage['from']) ?></p>
                <p class="item-msg item-msg-message"><span><?php echo $this->__('Message') ?>:</span> <?php echo $this->escapeHtml($hamperMessage['message']) ?></p>
            </div>
        </td>
        <td>&nbsp;</td>
        <?php if ($canApplyMsrp): ?>
            <td <?php if ($this->helper('tax')->displayCartBothPrices()): ?> colspan="2"<?php endif; ?>>&nbsp;</td>
        <?php else: ?>

            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <td>&nbsp;</td>
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <td>&nbsp;</td>
            <?php endif; ?>
        <?php endif; ?>
        <?php if (($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
            <td>&nbsp;</td>
        <?php endif; ?>
        <td>&nbsp;</td>
    </tr>
<?php } ?>
<?php } ?>
