<?php
/* @var $this Mage_Core_Block_Template */
?>
</td>
</tr>
<!--<tr>
    <td height="19">
        <img src="<?php echo $this->getBaseUrl()."media/email/images/blank.gif"; ?>" border="0" height="19" />
    </td>
</tr>-->
<tr>
    <td height="21">
        <table width="650" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td width="271"><img src="<?php echo $this->getBaseUrl()."media/email/images/blank.gif"; ?>" height="21" width="271" border="0"/></td>
                <td width="29"><a href="http://www.facebook.com/GRI.CentralCentralShop" target="_ccfb"><img src="<?php echo $this->getBaseUrl()."media/email/images/facebook.gif"; ?>" border="0"/></a></td>
                <td width="30"><a href="http://instagram.com/centralcentralshop" target="_ccig"><img src="<?php echo $this->getBaseUrl()."media/email/images/instagram.gif";?>" border="0"/></a></td>
                <td width="320"><a href="http://www.youtube.com/user/HKCentralCentral?sub_confirmation=1" target="_ccyt"><img src="<?php echo $this->getBaseUrl()."media/email/images/youtube.gif";?>" border="0"/></a></td>
            </tr>
        </table>
    </td>
</tr>
<tr>
    <td height="10">
        <span style="font-size:0pt"></span>
    </td>
</tr>
<tr>
    <td height="11" align="center" style="text-align="center;">
    <a href="<?php echo $this->getBaseUrl();?>" target="_ccshop"><img src="<?php echo $this->getBaseUrl()."media/email/images/footer_ccshop.gif";?>" border="0"/></a>
    </td>
</tr>
<!-- footer message -->
<tr>
    <td style="text-align:center;width:100%;color:#818181;font-size:11px;line-height:20px; font-family:Arial;">
        Tel: <a href="tel:%2B852-2480-2888" value="+85224802888" target="_blank">+852-2480-2888</a>, available on Monday - Friday, 9AM - 6PM,<br>excluding Hong Kong public holidays<br>Email:<a href="mailto:cs@ccshop.com" style="text-decoration:none;color:#818181" target="_blank">cs@ccshop.<wbr>com</a><br><br>
        # Please do not reply to this email. For any inquiries or concerns, please email us.<br>©2014 CC SHOP. All Rights Reserved.
    </td>
</tr>
</table>
