<style>
	.product-options{
		position: inherit !important;
	}

	.freegift{
		width: 330px;
		display: inline-block;
		margin:10px 0;
		border: 1px solid #e4e4e4;
	}

	.product-tootip-title{
		border-bottom: 1px dashed #A2A2A2;
		float: left;
		padding-bottom: 10px;
		width: 100%;
	}

	.product-tootip-head{
		width: 100%;
		float:left;
	}

	#label-freegift{
		float: left;
		padding: 10px 0 0 10px;
	}

	.rule-name{
		float: left;
		padding: 20px 0 0 20px;
		width: 60%;
	}

	.product-rule-description{
		float: left;
		clear: both;
		padding: 0 0 0 80px;
	}

	.product-tootip-content{
		clear: both;
		float: left;
		margin-left: 4px;
		width: 100%;
	}

	.product-tootip-gift-list{
		padding: 5px;
	}

	.product-gift-image{
		width: auto !important;
		height: auto !important;
		text-decoration: none !important;
	}

	.product-gift-image img{
		border: 1px solid #D4D4D4;
		margin-bottom: 5px;
		padding: 10px;
	}

	.gift-tootip{
		background-color: #ffffff;
		border-radius: 7px;
		box-shadow: 2px 4px 17px rgb(179, 184, 183);
		border: 1px solid rgb(199, 203, 204);
		padding: 10px;
		width: 160px;
	}

	.tootip-title{
		border-bottom: 1px dotted #959595;
		color: #2F2F2F;
		font-size: 12px;
		font-style: italic;
		font-weight: bold;
		margin-bottom: 5px;
		padding: 0 0 5px;
	}

	.label-product{
		font-size: 14px;
		font-weight: bold;
		font-style:italic;
	}

</style>
<?php
	$_ruleProducts = Mage::getSingleton('promotionalgift/catalogrule');
	$productId = $this->getCurrentProduct()->getId();
	//$_products= Mage::getModel('catalog/product');
	$freeGifts = $this->getIdFreeGifts($productId);
	$icon_image = Mage::helper('promotionalgift')->getPromotionalIcon();
	$iconUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'promotionalgift/giftlabel/' . $icon_image;
?>
<?php if($this->getRuleByPruduct($productId)):?>
<div id="divider"></div>
<div class="freegift" id="freegift">
<?php

	$ruleId = $this->getRuleByPruduct($productId)->getId();
	$_ruleProduct = $_ruleProducts->load($ruleId);
?>

		<div class="product-tootip-title">
			<div class="product-tootip-head">
				<img width="50px" id="label-freegift" src="<?php echo $iconUrl?>" alt="Label Free Gift"/>
				<div class="rule-name">
					<h3><?php echo $_ruleProduct->getData('name');?></h3>
				</div>
			</div>
			<div class="product-rule-description"><?php echo $_ruleProduct->getData('description')?></div>
		</div>
		<div class="product-tootip-content">
			<div class="product-tootip-gift-list">
				<?php foreach ($freeGifts as $_freegift):?>
					<?php $_product = Mage::getModel('catalog/product')->load($_freegift);
					?>
					<a id="product_<?php echo $_product->getId()?>" href="<?php echo $_product->getProductUrl() ?>"
					title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
					class="product-gift-image">
						<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(80); ?>"
							width="81" height="81" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
						/>
					</a>
				<?php endforeach;?>
			</div>
		</div>
</div>
<!--create tooltip for gift items-->
<?php foreach ($freeGifts as $_giftItem): ?>
	<div id="gift_information_<?php echo $_giftItem?>" class="gift-tootip" style="visibility: visible;">
		<div class="gift-tootip-main">
			<div class="tootip-title">
				<div class="tootip-head">
					<?php $giftProduct = Mage::getModel('catalog/product')->load($_giftItem);?>
					<?php $catalogRule = $this->getRuleByPruduct($_giftItem)?>
					<h4><?php echo $this->__('Extra Gift')?></h4>
				</div>
			</div>
			<div class="tootip-content">
					<div class="label-product"><?php echo $this->__(''.$this->stripTags($this->getImageLabel($giftProduct, 'small_image'), null, true))?></div>
					<div class="price-box">
						<p class="old-price">
							<?php echo Mage::helper('core')->formatPrice($giftProduct->getFinalPrice());?>
						</p>
					</div>
					<img class="tootip-content-img" src="<?php echo $this->helper('catalog/image')->init($giftProduct, 'small_image')->resize(157); ?>"
						width="157" height="145" alt="<?php echo $this->stripTags($this->getImageLabel($giftProduct, 'small_image'), null, true) ?>"
					/>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		var giftTootip_<?php echo $_giftItem?> = new Tooltip('product_<?php echo $_giftItem?>', 'gift_information_<?php echo $_giftItem?>');
	</script>
<?php endforeach;?>
<?php endif;?>



