<script type="text/javascript">
    //<![CDATA[
    var quoteBaseGrandTotal = <?php echo (float)$this->getQuoteBaseGrandTotal(); ?>;
    var checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
    var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
    var lastPrice;
    payment.save = function () {
        if (checkout.loadWaiting != false) return;
        var validator = new Validation(this.form);
        if (this.validate() && validator.validate()) {
            checkout.setLoadWaiting('payment');
            var request = new Ajax.Request(
                this.saveUrl,
                {
                    method: 'post',
                    onComplete: this.onComplete,
                    onSuccess: function (e) {
                        checkout.setLoadWaiting(false, true);
                        $('payment-please-wait').show();
                        review.save();
                    },
                    onFailure: checkout.ajaxFailure.bind(checkout),
                    parameters: Form.serialize(this.form)
                }
            );
        }
    };

    //]]>
</script>
<form action="" id="co-payment-form">
    <fieldset>
        <?php echo $this->getChildHtml('methods') ?>
    </fieldset>
</form>
<div class="tool-tip" id="payment-tool-tip" style="display:none;">
    <div class="btn-close"><a href="#" id="payment-tool-tip-close"
                              title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
    <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>"
                                       alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>"
                                       title="<?php echo $this->__('Card Verification Number Visual Reference') ?>"/>
    </div>
</div>
<div class="buttons-set" id="payment-buttons-container">
    <!--    <p class="required">--><?php //echo $this->__('* Required Fields') ?><!--</p>-->
    <!--    <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small>-->
    <?php //echo $this->__('Back') ?><!--</a></p>-->
    <button type="button" class="button" onclick="payment.save()"><span><span><?php echo $this->__('Place Order') ?></span></span>
    </button>
    <span class="please-wait" id="payment-please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
             alt="<?php echo $this->__('Loading next step...') ?>"
             title="<?php echo $this->__('Loading next step...') ?>"
             class="v-middle"/> <?php echo $this->__('Loading next step...') ?>
    </span>
    <p class="payment-tips"><?php echo $this->helper('gri_catalogcustom')->__('You will be required to enter your payment details after you place an order.') ?></p>
</div>

<div class="paypal-image">
    <img src="<?php echo $this->getSkinUrl('images/paypal-creditcard.png');?>" />
</div>

<script type="text/javascript">
    //<![CDATA[
    function toggleToolTip(event) {
        if ($('payment-tool-tip')) {
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event) - 560) + 'px'//,
                //left: (Event.pointerX(event)+100)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if ($('payment-tool-tip-close')) {
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
    //]]>
</script>
<script type="text/javascript">
    //<![CDATA[
    payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
    //]]>
</script>
