<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Rma
 * @version    1.3.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>

<?php $_formData = $this->getFormData() ?>
<div class="awrma-account">
    <div class="page-title">
        <h1><?php echo $this->__('Add New Request') ?></h1><a href="javascript:void(0)" class="dashboard-dropdown-menu"></a>
    </div>
    <div id="messages">
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    </div>
    <?php if ($this->getGuestMode() || $this->getCustomerOrders()->getSize()) : ?>
        <form action="<?php echo $this->getGuestMode() ? $this->getUrl('awrma/guest_rma/save') : $this->getUrl('awrma/customer_rma/save') ?>" method="post" id="awrma-new-form" enctype="multipart/form-data">
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="fieldset">
                <ul class="form-list">
                    <li class="wide">
                        <label for="awrma-order" class="required"><?php echo $this->__('Your Order') ?></label>
                        <div class="input-box">
                            <select type="select" name="order" id="awrma-order" title="<?php echo $this->__('Order') ?>" class="validate-select required-entry" defaultvalue="" isVisible="1">
                                <option value=""><?php echo $this->__('Please select order') ?></option>
                                <?php foreach ($this->getCustomerOrders() as $order) : ?>
                                    <option value="<?php echo $order->getIncrementId(); ?>" <?php if (isset($_formData['order']) && $_formData['order'] == $order->getIncrementId()) : ?>selected="selected"<?php endif; ?>>
                                        <?php echo '#' . $order->getIncrementId() . ', ' . $this->formatDate($order->getCreatedAtStoreDate()) . ', ' . $order->formatPrice($order->getGrandTotal()) ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>

                        </div>
                    </li>
                    <li class="wide">
                        <!--<label for="awrma-items-ordered-table"><?php echo $this->__('Items Ordered') ?></label><br/>-->
                        <p><?php echo $this->__('Item(s) needed to return.') ?></p>
                        <div class="input-box">
                            <table class="data-table" id="awrma-items-ordered-table" name="items">
                                <thead id="awrma-items-head">
                                    <tr>
                                        <th><?php echo $this->__('Item Description') ?></th>
                                        <th><?php echo $this->__('Ref No.') ?></th>
                                        <th><?php echo $this->__('Color') ?></th>
                                        <th><?php echo $this->__('Size') ?></th>
                                        <th><?php echo $this->__('Quantity') ?></th>
                                        <?php if (Mage::helper('awrma/config')->getAllowPerOrderRMA()) : ?><th></th><?php endif; ?>
                                    </tr>
                                    <tr id="awrma-items-noorder" style="display: none;">
                                        <td colspan="6"><?php echo $this->__('No order selected') ?></td>
                                    </tr>
                                    <tr id="awrma-items-noitems" style="display: none;">
                                        <td colspan="6"><?php echo $this->__('No items selected') ?></td>
                                    </tr>
                                    <tr id="awrma-items-loading" style="display: none;">
                                        <td colspan="6"><img src="<?php echo $this->getSkinUrl('aw_rma/images/ajax-loader.gif') ?>" /></td>
                                    </tr>
                                    <tr id="awrma-items-error" style="display: none;">
                                        <td colspan="6"><?php echo $this->__('Some error occurs. Please, try again to select order') ?></td>
                                    </tr>
                                </thead>
                                <tbody id="awrma-items">
                                    <tr>
                                        <td colspan="6"><?php echo $this->__('No order selected') ?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </li>
                    <li class="fields">
                        <?php $_types = $this->getRequestTypes() ?>
                        <?php if ($_types->getSize()) : ?>
                            <div class="field">
                                <label for="awrma-request-type" class="required"><?php echo $this->__('Request Type') ?></label>
                                <div class="input-box">
                                    <?php $_itemSelected = isset($_formData['requesttype']) ? $_formData['requesttype'] : '' ?>
                                    <select type="select" name="requesttype" id="awrma-request-type" title="<?php echo $this->__('Request Type') ?>" class="validate-select required-entry" isVisible="1">
                                        <option value=""><?php echo $this->__('Please select') ?></option>
                                        <?php foreach ($_types as $_item) : ?>
                                            <option value="<?php echo $_item->getId() ?>" <?php if ($_item->getId() == $_itemSelected) : ?>selected="selected" <?php endif; ?>><?php echo $_item->getName() ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                        <?php endif ?>
                        <div class="field">
                            <label for="awrma-packageopened" class="required"><?php echo $this->__('Package Opened') ?></label>
                            <div class="input-box">
                                <?php foreach (Mage::getModel('awrma/source_packageopened')->toOptionArray() as $_item) : ?>
                                    <input type="radio" value="<?php echo $_item['value'] ?>" name="PackageOpen"> <span><?php echo $_item['label'] ?></span>
                                <?php endforeach; ?>
                                <?php /*
                                <select type="select" name="packageopened" id="awrma-packageopened" title="<?php echo $this->__('Package Opened') ?>" class="validate-select required-entry" isVisible="1">
                                    <?php $_itemSelected = isset($_formData['packageopened']) ? $_formData['packageopened'] : Mage::getModel('awrma/source_packageopened')->getDefaultValue(); ?>
                                    <option value="">&#8203;</option>
                                    <?php foreach (Mage::getModel('awrma/source_packageopened')->toOptionArray() as $_item) : ?>
                                        <option value="<?php echo $_item['value'] ?>"><?php echo $_item['label'] ?></option>
                                    <?php endforeach; ?>
                                </select>
                                 */ ?>
                            </div>
                        </div>
                    </li>
                    <li class="wide additional-information">
                        <label for="awrma-additional-info"><?php echo $this->__('Return Reason') ?></label>
                        <div class="input-box">
                            <textarea name="additionalinfo" id="awrma-additional-info" class="required-entry"><?php if (isset($_formData['additionalinfo']))
                        echo $_formData['additionalinfo'] ?></textarea>
                        </div>
                    </li>
                    <li class="fields">
                        <label for="awrma-file-upload"><?php echo $this->__('For defective merchandise, please upload a photo') ?></label>
                          <div class="field attachment">
                               <!--<label for="awrma-file-upload"><?php echo $this->__('Attachment') ?></label>-->
                                 <div class="input-box">
                                     <!-- <input type="file" id="awrma-file-upload" name="attachedfile" value="Upload"/>-->
                                     <input type='text' name='textfield' id='textfield' class='awrma-file-txt' />
                                     <input type='button' class='awrma-file-btn' value='<?php echo $this->__("Upload") ?>' onclick="jQuery('#awrma-file-upload').click()" />
                                     <input type="file" name="fileField" id="awrma-file-upload" class="awrma-file-file" onchange="document.getElementById('textfield').value=this.value" />
                                 </div>
                         </div>
                    </li>
                </ul>
            </div>
            <div class="buttons-set">
                <!--<p class="required"><?php echo $this->__('* Required Fields') ?></p>-->
                <button type="submit" title="<?php echo $this->__('Submit Request') ?>" class="button" id="awrma-new-submit"><span><?php echo $this->__('Submit') ?></span></button>
            </div>
        </form>
        <script type="text/javascript">
            //&lt;![CDATA[
            var awrmaNewForm = new VarienForm('awrma-new-form', true);
            var ordersControl = new AWRMAOrdersControl(this, awrmaNewForm, "<?php echo $this->getGuestMode() ? $this->getUrl('awrma/guest_rma/getitemsfororder') : $this->getUrl('awrma/customer_rma/getitemsfororder') ?>");
            $('awrma-order').onchange = ordersControl.orderChanged.bind(ordersControl);
                    //]]&gt;
        </script>
    <?php else : ?>
        <p><?php echo $this->__('You have no completed orders to request RMA or your orders were placed more than %s days ago', Mage::helper('awrma/config')->getDaysAfter()); ?></p>
<?php endif; ?>
</div>
