<?php /* @var $this Mage_Reports_Block_Product_Viewed */ ?>
<?php $products = $this->getRecentlyViewedProducts(); ?>
<?php if(count($products)): ?>
    <div class="most-recent-views" id="most-recent-views">
        <h2><span><?php echo $this->__('Most Recent Views'); ?></span></h2>
        <a class="prev" href="javascript:void(0);" style="cursor: pointer;">&lt;</a>
        <div class="jcarousel">
            <ul class="slider clearer">
                <?php foreach( $products as $product ){ ?>
                    <li class="slide item">
                        <?php
                            echo Mage::helper('gri_catalogcustom/product')->getProductListItemBlock()
                                            ->setProduct($product)
                                            ->setShowActions(FALSE)
//                                          ->setImageWidth(150)
//                                          ->setImageHeight(150)
                                            ->setShowColorSwatch(FALSE)
                                            ->toHtml();
                        ?>
                    </li>
                <?php } ?>
            </ul>
        </div>
        <a class="next" href="javascript:void(0);" style="cursor: pointer;">&gt;</a>
    </div>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl('js').'jquery/jquery.iosslider.min.js' ?>"></script>
    <script type="text/javascript">
        (function($) {
            var scroll = $('#most-recent-views .jcarousel'), slider = scroll.children('ul');
            slider.css({height: slider.children('li').height()+100});
            scroll.iosSlider({
                infiniteSlider: true,
                snapToChildren: true,
                navNextSelector: scroll.siblings('.next'),
                navPrevSelector: scroll.siblings('.prev')
            });
        })(jQuery);
    </script>
    <script type="text/javascript">
        decorateGeneric($$('ul.slider li'), ['odd','even','first','last']);
    </script>
<?php endif; ?>
