<?php
/* @var $this Gri_Sales_Block_Order_Print */
?>
<?php echo $this->getChildHtml('sales.order.confirmation.top') ?>
<div class="order-items order-details">
    <?php if ($this->helper('giftmessage/message')->getIsMessagesAvailable('items', $this->getOrder())): ?>
        <script type="text/javascript">
            //<![CDATA[
            function giftMessageToogle(giftMessageIdentifier) {
                var link = $('order-item-gift-message-link-' + giftMessageIdentifier);
                var container = $('order-item-gift-message-' + giftMessageIdentifier);
                var row = $('order-item-row-' + giftMessageIdentifier);
                if (link.expanded) {
                    link.expanded = false;
                    link.removeClassName('expanded');
                    if (container.hasClassName('last')) {
                        row.addClassName('last');
                    }
                    container.hide();
                } else {
                    link.expanded = true;
                    link.addClassName('expanded');
                    if (container.hasClassName('last')) {
                        row.removeClassName('last');
                    }
                    container.show();
                }

                return false;
            }
            //]]>
        </script>
    <?php endif; ?>
    <?php $_order = $this->getOrder() ?>
    <?php if(0): ?>
        <h2 class="table-caption"><?php echo $this->__('Items Ordered') ?>
            <?php if ($_order->getTracksCollection()->count()) : ?>
                <span class="separator">|</span> <a href="#" onclick="popWin('--><?php //echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?><!--','trackorder','top=0,left=0,width=800,height=600,resizable=yes,scrollbars=yes'); return false;" title="<?php echo $this->__('Track your order') ?><!--">--><?php echo $this->__('Track your order') ?></a>
                <?php endif;
            ?>
        </h2>
    <?php endif; ?>

    <?php echo $this->getChildHtml('order_items') ?>

    <?php if ($this->helper('giftmessage/message')->getIsMessagesAvailable('order', $_order) && $_order->getGiftMessageId()): ?>
        <div class="order-additional order-gift-message">
            <h2 class="sub-title"><?php echo $this->__('Gift Message for This Order') ?></h2>
            <?php $_giftMessage = $this->helper('giftmessage/message')->getGiftMessageForEntity($_order); ?>
            <dl class="gift-message">
                <dt>
                    <strong><?php echo $this->__('From:') ?></strong> <?php echo $this->htmlEscape($_giftMessage->getSender()) ?>
                </dt>
                <dt>
                    <strong><?php echo $this->__('To:') ?></strong> <?php echo $this->htmlEscape($_giftMessage->getRecipient()) ?>
                </dt>
                <dd><?php echo $this->helper('giftmessage/message')->getEscapedGiftMessage($_order) ?></dd>
            </dl>
        </div>
    <?php endif; ?>
    <?php $_history = $this->getOrder()->getVisibleStatusHistory() ?>
    <?php if (count($_history)): ?>
        <div class="order-additional order-comments">
            <h2 class="sub-title"><?php echo $this->__('About Your Order') ?></h2>
            <dl class="order-about">
                <?php foreach ($_history as $_historyItem): ?>
                    <dt><?php echo $this->formatDate($_historyItem->getCreatedAtStoreDate(), 'medium', true) ?></dt>
                    <dd><?php echo $this->escapeHtml($_historyItem->getComment()) ?></dd>
                <?php endforeach; ?>
            </dl>
        </div>
    <?php endif; ?>
    <?php /*
        <div class="buttons-set">
            <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->getBackTitle() ?></a></p>
        </div>
        */
    ?>
</div>
<div class="customer-remarks">
    <h2 class="remarks-title"><?php echo $this->__('Customer Remarks') ?></h2>
    <p class="remarks-content"><?php echo $_order->getRemarks() ?></p>
</div>

<div class="order-bottom">
    <?php /*
    <?php if(0): ?>
        <p class="domain">CCSHOP.COM</p>
        <p class="discount"><?php echo $this->__('Tel %s',' +852-2480-2888') ;?>  <?php echo $this->__('Email %s', 'cs@centralcentralshop.com')?></p>
    <?php endif;?>
    <p class="shipping-delivery"><?php echo $this->__('For more shipping information, please click ') ?>
        <a href="#"><?php echo $this->__('Shipping and Delivery') ?></a></p>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('acc_order_bottom_text')->toHtml() ?>
    */?>
    <h2>CCSHOP.COM</h2>
    <div><?php echo $this->__('Tel');?> +852-2480-2888　/　<?php echo $this->__('Email') ?>　cs@ccshop.com</div>
</div>

<script type="text/javascript">//decorateTable('my-orders-table', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
<script type="text/javascript">
        window.print();
</script>