<?php
/* @var $_item Gri_SalesRule_Model_Quote_Item */
$_item = $this->getItem();

$_product = $_item->getProduct();
$color = $size = '';

$_parentProduct = $this->getParentOfGift();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);

/* @var $swatchHelper Magiatec_Colorswatch_Helper_Swatch */
$swatchHelper = Mage::helper('magiatecolorswatch/swatch');
$swatchHelper->setCurrentProduct($_product);

/*@var $_taxHelper Mage_Tax_Helper_Data */
$_taxHelper = $this->helper('tax');

 /* @var $helper ProxiBlue_GiftPromo_Helper_Product_Configuration */
$helper = Mage::helper('giftpromo/product_configuration');
$_options = $helper->getConfigurableOptions($_item);

foreach ($_options as $_option) {
    if (isset($_option['code']) && (substr($_option['code'], 0, 5) == 'color')) {
        $color = $_option['value'];
        continue;
    }

    if (isset($_option['code']) && (substr($_option['code'], 0, 4) == 'size')) {
        $size = $_option['value'];
        continue;
    }
}
?>
<tr>
    <td><img src="<?php echo $this->getProductThumbnail()->resize(75); ?>" width="75" height="75" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" /></td>
    <td>
        <p class="brand up_c"><?php echo $_product->getAttributeText('brand'); ?></p>
        <p class="product-name">
            <?php if ($this->hasProductUrl()):?>
                <a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->htmlEscape($this->getProductName()) ?></a>
            <?php else: ?>
                <?php echo $this->htmlEscape($this->getProductName()) ?>
            <?php endif; ?>
        </p>
        <p class="product-sku f11 grey"><span><?php echo $this->__('SKU#:'); ?></span>&nbsp;<?php echo $_product->getSku(); ?></p>
    </td>
    <td style="width:100px">
        <?php echo $size; ?>
    </td>
    <td style="width:100px">
        <?php echo $color; ?>
    </td>
    <td style="width:120px;">
        <?php echo $this->getQty() ?>
    </td>

    <td class="width:100px">
        <?php $_finalPrice = $_taxHelper->getPrice($_product, $_product->getFinalPrice());?>

        <span class="cart-price del">
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
            <?php else: ?>
                <?php echo $this->helper('checkout')->formatPrice($_item->getProduct()->getPrice()); ?>
            <?php endif; ?>
        </span>
         <p><span class="free"><?php  echo  $_finalPrice == 0 ? $this->__('free') : $this->helper('checkout')->formatPrice($_finalPrice); ?></span></p>
    </td>
    <td style="width:120px" class="right_al">
        <?php /* @var $this ProxiBlue_GiftPromo_Block_Cart_Item_Renderer_Configurable */ ?>
        <?php if($this->canDelete()): ?>
         <p>
             <a href="<?php echo $this->getDeleteUrl()?>" title="<?php echo $this->__('Remove item')?>" class="rig_txt cart_remove_btn"><?php echo $this->__('Remove')?></a>
         </p>
        <?php endif; ?>    
    </td>
</tr>
