<?php
/* @var $_item Gri_SalesRule_Model_Quote_Item*/
$_item = $this->getItem();

/* @var $_product Gri_CatalogCustom_Model_Product*/
$_product = $_item->getProduct();

$attributeSetName = Mage::getModel('eav/entity_attribute_set')
                       ->load($_product->getAttributeSetId())
                       ->getAttributeSetName();
$size = $color= '';
$color = $_product->getAttributeText('color_code');
if(in_array(strtolower($attributeSetName),array('shoes','clothing'))) {
    $size = $_product->getAttributeText('size_'.strtolower($attributeSetName));
}


$this->compositeMessage();
$_parentProduct = $this->getParentOfGift();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$_taxHelper = $this->helper('tax');
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>
<tr>
    <td><?php if ($this->hasProductUrl()):?><a href="<?php echo $this->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getProductName()) ?>" class="product-image"><?php endif;?><img src="<?php echo $this->getProductThumbnail()->resize(75); ?>" width="75" height="75" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" /><?php if ($this->hasProductUrl()):?></a><?php endif;?></td>
    <td>
        <p class="brand up_c"><?php echo $_product->getAttributeText('brand'); ?></p>
        <p class="product-name">
        <?php if ($this->hasProductUrl()):?>
            <a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->htmlEscape($this->getProductName()) ?></a> 
        <?php else: ?>
            <?php echo $this->htmlEscape($this->getProductName()) ?>
        <?php endif; ?>
        </p>
        <p class="product-sku f11 grey"><span><?php echo $this->__('SKU#:'); ?></span>&nbsp;<?php echo $_product->getSku(); ?></p>
        <?php if ($_options = $this->getOptionList() & 0):?>
        <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
            <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
            <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                <div class="truncated_full_value">
                    <dl class="item-options">
                        <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
                        <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                    </dl>
                </div>
                <?php endif; ?>
            </dd>
            <?php endforeach; ?>
        </dl>
        <?php endif;?>
        <?php if ($messages = $this->getMessages()): ?>
           <?php foreach ($messages as $message): ?>
<!--              <p class="item-msg --><?php //echo $message['type'] ?><!--">* --><?php //echo $this->htmlescape($message['text']) ?><!--</p>-->
           <?php endforeach; ?>
        <?php endif; ?>
        <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock): ?>
            <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif;?>
    </td>
    <td style="width:100px">
        <?php echo $size; ?>
    </td>
    <td style="width:100px">
        <?php echo $color; ?>
    </td>
    <td style="width:120px;">
        <?php echo $this->getQty() ?>
    </td>
    <td style="width:100px">
        <span class="cart-price del">
            <?php echo $this->helper('checkout')->formatPrice($_product->getPrice()); ?>
        </span>
        <?php $_finalPrice =  $_taxHelper->getPrice($_product, $_product->getFinalPrice());
        ?>
        <p><span class="free"><?php echo $_finalPrice == 0 ? $this->__('free') :  $this->helper('checkout')->formatPrice($_finalPrice); ?></span></p>
    </td>

    <?php if (($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
    <td>
        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>
            <?php if ($canApplyMsrp): ?>
                <span class="cart-msrp-subtotal">--</span>
            <?php else: ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?>
                <?php else: ?>
                    <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
                <?php endif; ?>
            <?php endif; ?>
        </span>
    </td>
    <?php endif; ?>
    <td class="right_al" width="120px">
        <?php if($this->canDelete()): ?>
            <p>
                <a href="<?php echo $this->getDeleteUrl()?>" title="<?php echo $this->__('Remove item')?>" class="rig_txt cart_remove_btn"><?php echo $this->__('Remove')?></a>
            </p>
        <?php endif; ?>
    </td>
</tr>
