<div class="product-image-moreview left">
    <?php if (count($this->getGalleryImages()) > 0): ?>
        <div class="carousel-01">
            <a href="javascript:void(0);" class="prev" id="prev-05">&nbsp;</a>

            <div class="jCarouselLite-01" id="thumbnail">
                <ul>
                    <?php foreach ($this->getGalleryImages() as $_image): ?>
                        <li>
                            <a href="#"
                               onclick="popWin('<?php echo $this->getGalleryUrl($_image) ?>', 'gallery', 'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;"
                               title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img
                                    src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>"
                                    width="56" height="56" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <div style="clear:both;"></div>
            <a href="javascript:void(0);" class="next" id="next-05">&nbsp;</a>
        </div><!--carousel end-->

        <script type="text/javascript">
            (function ($) {
                $('#thumbnail').jCarouselLite({
                    btnPrev: '#prev-05',
                    btnNext: '#next-05',
                    visible: 3,
                    vertical: true,
                    easing: "bounceout",
                    speed: 1000
                });
            })(jQuery)
        </script>
    <?php endif; ?>
</div>