<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Rma
 * @version    1.3.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php
?>

<div class="awrma-account">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Return Request') ?></h1>
    </div>
    <script>
        (function($){
            $('.main-container').prepend($('.page-title'));
        })(jQuery)
    </script>
    <!--<p><?php echo $this->__('Selecting folowed links to view or edit information.')?></p>-->
    <div class="title-buttons"><a class="link-awrma-newrma" href="<?php echo $this->getUrl('awrma/customer_rma/new') ?>"><?php echo $this->__('New Return Request') ?></a></div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php if ($this->getRmaEntitiesCollection()->getSize()) : ?>
    <table class="data-table" id="my-rmas-table">
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col />
        <col width ="1"/>
        <thead>
        <tr>
            <th><?php echo $this->__('Date') ?></th>
            <th><?php echo $this->__('Ticket No.') ?></th>
            <th><?php echo $this->__('Order No.') ?></th>
            <th style="width:46%;"><?php echo $this->__('Status') ?></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
            <?php foreach ($this->getRmaEntitiesCollection() as $item) : ?>
        <tr>
            <td><?php echo $this->helper('core')->formatDate($item->getCreatedAtDate(), 'long') ?></td>
            <td><?php echo $item->getTextId() ?></td>
            <td>#<?php echo $item->getOrderId() ?></td>
            <td><?php echo $item->getStatusName() ?></td>
            <td><div class="request_operator">
                <a href="<?php echo $this->getUrl('awrma/customer_rma/view', array('id' => $item->getId())) ?>" class="link-awrma-bold"><?php echo $this->__('View Request') ?></a>
                <?php if ($item->getIsActive()) : ?>
                <a class="link-awrma" href="<?php echo $this->getUrl('awrma/customer_rma/cancel', array('id' => $item->getId())) ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to cancel this RMA?') ?>')" class="link-awrma-cancel"><?php echo $this->__('Cancel') ?></a>
                <?php endif; ?>
            </div>
            </td>
        </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php echo $this->getChildHtml('pager'); ?>
    <script type="text/javascript">decorateTable('my-rmas-table')</script>
    <?php else : ?>
    <p><?php echo $this->__('You have no RMA requests'); ?></p>
    <?php endif; ?>
</div>
