<?php
/* @var $this Gri_FlashSale_Block_CountDown */
?>
<div class="fl_time_title_mobile" style="display: none;">
    <span><?php echo $this->__('Ends in'); ?></span> - <span id="flash-sale-countdown-mobile" class="clearer"></span>
</div>
<script type="text/javascript">
    jQuery(function () {
        jQuery("#flash-sale-countdown-mobile").countdown({
            date: "<?php echo $this->getNewStartTime(); ?>",
            render: function(data) {
                var el = jQuery(this.el);
                var y = this.leadingZeros(data.years, 4)
                var d = this.leadingZeros(data.days, 3)
                var h = parseInt(this.leadingZeros(data.hours, 2)) + parseInt(y * 365 * 24 + d * 24)
                var m = this.leadingZeros(data.min, 2)
                var s = this.leadingZeros(data.sec, 2)
                el.empty().append(h + " <span>:</span> " +  m + " <span>:</span> " + s)
            }
        })
    })
</script>
