<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Rma
 * @version    1.3.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2010 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/* @var $this Mage_Sales_Block_Order_Info */
/* @var $_griSalesHelper Gri_Sales_Helper_Data */
$_griSalesHelper = $this->helper('gri_sales');
?>
<?php $_order = $this->getOrder() ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title title-buttons">
    <div class="action right f11">
        <?php if ($_order->getStatus() == 'pending') if ($_payUrl = $_griSalesHelper->getPaymentUrl($_order)) { ?>
            <a href="<?php echo $_payUrl ?>" class="link-payment"><?php echo $this->__('Pay') ?></a>
        <?php } ?>
        <?php /* if ($this->helper('rss/order')->isStatusNotificationAllow()): ?>
            <a href="<?php echo $this->helper('rss/order')->getStatusHistoryRssUrl($_order) ?>" class="link-rss"><?php echo $this->__('Subscribe to Order Status') ?></a>
            <span class="separator">|</span>
        <?php endif; */?>
        <?php if ($_payNowUrl = $_griSalesHelper->getPayNowUrl($_order)) { ?>
            <a href="<?php echo $_payNowUrl ?>" class="link-pay-now"><?php echo $this->__('Pay Now') ?></a>
        <?php } else if ($this->helper('sales/reorder')->canReorder($_order)) { ?>
            <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
        <?php } /*?>
        <a href="<?php echo $this->getPrintUrl($_order) ?>" class="link-print" onclick="this.target='_blank';"><?php echo $this->__('Print Order') ?></a>
        <?php if (Mage::helper('awrma')->isEnabled() && Mage::helper('awrma')->isAllowedForOrder($_order)) : ?>
            <a href="<?php echo $this->getUrl('awrma/customer_rma/createfororder/', array('order_id' => $_order->getIncrementId())) ?>" class="link-print"><?php echo $this->__('Request RMA') ?></a>
        <?php endif */ ?>
    </div>
    <h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h1>
</div>
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<div class="order_detail">
    <!--<dl class="order-info">
    <?php /*<dt><?php echo $this->__('About This Order:') ?></dt> */ ?>
    <dd>
        <?php $_links = $this->getLinks(); ?>
        <ul id="order-info-tabs">
            <?php foreach ($_links as $_link): ?>
                <?php if ($_link->getUrl()): ?>
                    <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php else: ?>
                    <li class="current"><?php echo $_link->getLabel() ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateGeneric($('order-info-tabs').select('LI'),['first','last']);</script>
    </dd>
</dl-->
<p class="order-date"><?php echo $this->__('Order Date: %s', $_order->getCreatedAtStoreDate()) ?></p>
<div class="clear"></div>
</div>
<?php if (!$_order->getIsVirtual()): ?>
    <div class="col2-set order-info-box">
        <div class="col-1">
            <div class="box">
                <div class="box-title">
                    <h2><?php echo $this->__('Shipping Address') ?></h2>
                </div>
                <div class="box-content">
                    <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
                    <?php if($_order->getData('fapiao')) :?>
                    <p class="fapiao"><span><?php echo $this->__('Invoice Title') ?>: <?php echo $_order->getData('fapiao')?></span></p>
                    <?php endif;?>
                </div>
            </div>
        </div>
        <div class="col-2">
            <div class="box">
                <div class="box-title">
                    <h2><?php echo $this->__('Delivery Method') ?><?php /* | <a href="#"><?php echo $this->__('Track Order') ?></a> */ ?></h2>
                </div>
                <div class="box-content">
                    <?php if ($_order->getShippingDescription()): ?>
                        <?php echo $_order->getShippingDescription() ?>
                    <?php else: ?>
                        <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
                    <?php endif; ?>
                    <?php if($_order->getData('remarks')) :?>
                    <p class="fapiao"><span><?php echo $this->__('Remarks') ?>: <?php echo $_order->getData('remarks')?></span></p>
                    <?php endif;?>
                    <?php if ($_order->getTracksCollection()->count()) foreach($_order->getTracksCollection() as $track) { ?>
                        <p class="tracking-info">
                            <?php echo $this->__('Waybill No.') ?>
                            <?php echo $this->escapeHtml($track->getTitle()) ?>:
                            <strong class="tracking-no"><?php echo $this->escapeHtml($track->getNumber()) ?></strong>
                            <?php if (!$track->isCustom()) { ?>
                                <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($track) ?>','trackorder','width=800,height=600,left=0,top=0,resizable=yes,scrollbars=yes');return false;" ><?php echo $this->__('Track your order') ?></a>
                            <?php } ?>
                        </p>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php /* <div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Billing Address') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box box-payment">
            <div class="box-title">
                <h2><?php echo $this->__('Payment Method') ?></h2>
            </div>
            <div class="box-content">
                <?php echo $this->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div> */ ?>
