<?php
/* @var $this Mage_Catalog_Block_Product_List_Related */
/* @var $product Mage_Catalog_Model_Product */
$this instanceof Mage_Reports_Block_Product_Viewed and $this->setItems($this->getRecentlyViewedProducts());
$this->getImageSize() or $this->setImageSize(125);
$count = count($this->getItems()) ;
?>
<div class="scroll <?php echo $this->getCssClass(); ?> clearer" id="scroll-<?php echo $this->getCssClass(); ?>">
    <?php if (!$this->getHideTitle()) { ?><h2><?php echo $this->__($this->getTitle()) ?></h2><?php } ?>
    <?php if($count>3):?>
      <a class="prev" href="javascript:void(0);">&lt;</a>
    <?php endif;?>
    <div class="jcarousel">
        <?php if($count) { ?>
        <ul>
            <?php foreach ($this->getItems() as $product) {
                $product->getAttributeText('brand') or $product->load(NULL);
                $image = Mage::helper('magiatecolorswatch/Swatch')->getFirstColorSwatchImage($product);
            ?>
            <li>
                <a href="<?php echo $product->getProductUrl() ?>">
                    <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image',$image)->resize($this->getImageSize()) ?>" alt="<?php echo $this->escapeHtml($product->getName()) ?>" />
                    <span class="text">
                        <span class="brand"><?php echo $product->getAttributeText('brand'); ?></span>
                        <br>
                        <span class="name"><?php echo $this->escapeHtml($product->getName()); ?></span>
                    </span>
                </a>
            </li>
            <?php } ?>
        </ul>
        <?php } ?>
    </div>
    <?php if($count>3):?>
      <a class="next" href="javascript:void(0);">&gt;</a>
    <?php endif; ?>
</div>
<?php if ($this->getVisible() && $count > $this->getVisible()) { ?>
<script type="text/javascript">
    (function($) {
        var scroll = $('#scroll-<?php echo $this->getCssClass(); ?> .jcarousel'), slider = scroll.children('ul');
        slider.css({height: slider.children('li').height()});
        scroll.iosSlider({
            snapToChildren: true,
            navNextSelector: scroll.siblings('.next'),
            navPrevSelector: scroll.siblings('.prev')
        });
    })(jQuery);
</script>
<?php } ?>
