<?php
/**
 * Customer "Remember Me" template
 *
 * @var $this Mage_Persistent_Block_Form_Remember
 */
?>
<?php $rememberMeId = 'remember_me' . Mage::helper('core')->getRandomString(10); ?>
<div class="input-box remember-me">
    <input type="checkbox" name="persistent_remember_me" class="checkbox selectBox" id="<?php echo $rememberMeId; ?>"<?php if ($this->isRememberMeChecked()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Remember Me') ?>" />
    <label for="<?php echo $rememberMeId; ?>"><?php echo $this->__('Remember me') ?></label>
</div>
