<?php /* @var $this Gri_Page_Block_Html_Topmessage */ ?>
<?php if($this->getIsHomePage() && $this->isEnabled()):?>
    <div id="page-top-message">
        <div class="page-top-message-wrapper">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('page_top_message')->toHtml() ?>
            <a href="javascript:;" class="page-top-close"></a>
        </div>

    </div>

    <script type="text/javascript">
        (function($){
            $("#page-top-message .page-top-close").click(function(){
                $("#page-top-message").hide();
                Mage.Cookies.set('<?php echo $this->getCookieName(); ?>', 1);
            });
        })(jQuery);
    </script>
<?php endif; ?>
