<?php /* @var $this Mage_Page_Block_Html_Header  */  ?>
<?php if (Mage::getSingleton('customer/session')->getCustomerId()): ?>
    <a href="<?php echo $this->getUrl('wishlist'); ?>" class="top-wishlist-link"><p class="top-wishlist-name"><?php echo  Mage::helper('gri_wishlist')->__('WishList'); ?></p>
        <span><?php echo Mage::helper('wishlist')->getItemCount(); ?></span>
    </a>
<?php endif; ?>
