<?php
/* @var $this Mage_Adminhtml_Block_Widget_Form_Renderer_Fieldset_Element */
/* @var $_element Gri_Reports_Block_Adminhtml_Form_Element_CategoryChooser */
$_element = $this->getElement();
$_note = $_element->getNote();
$_trId = $_element->getHtmlContainerId();
$_class = $_element->getFieldsetHtmlClass();
?>
<?php if (!$_element->getNoDisplay()): ?>
    <tr<?php if ($_trId): ?> id="<?php echo $_trId ?>"<?php endif; ?>>
        <?php if ($_element->getType() == 'hidden'): ?>
            <td colspan="2" class="hidden"><?php echo trim($_element->getElementHtml()) ?></td>
        <?php else: ?>
            <td class="label<?php echo $_class ? " {$_class}-label" : '' ?>"><?php echo trim($_element->getLabelHtml()) ?></td>
            <td class="<?php echo $_element->hasValueClass() ? $_element->getValueClass() : 'value' ?><?php echo $_class ? " {$_class}-value" : '' ?>">
                <ul><li>
                    <div class="rule-param"><div class="element">
                        <?php echo trim($_element->getElementHtml()) ?>
                        <a href="javascript:void(0);" class="rule-chooser-trigger"><img src="<?php echo $this->getSkinUrl('images/rule_chooser_trigger.gif'); ?>" class="v-middle rule-chooser-trigger" title="Open Chooser"/></a>
                        <?php if ($_note) { ?>
                            <p class="note<?php echo $_class ? " {$_class}-note" : '' ?>" id="note_<?php echo $_element->getId() ?>">
                                <span><?php echo $_note ?></span></p>
                        <?php } ?>
                        <span class="no-display rule-param-apply"></span>
                    </div></div>
                    <div class="rule-chooser" url="<?php echo $_element->getChooserUrl(); ?>"></div>
                </li></ul>
            </td>
        <?php endif; ?>
    </tr>
<?php endif; ?>
