<?php
/**
 * Temlate for Mage_Customer_Block_Address_Book block
 * @var $this Mage_Customer_Block_Address_Book
 */
?>
<?php
    $_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping();
    /* @var $_directoryHelper Gri_Directory_Helper_Data */
    $_directoryHelper = Mage::helper('gri_directory');
    $internalCode = $_directoryHelper->getInternalCode();
?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Address Book') ?></h1><a href="javascript:;" class="dashboard-dropdown-menu"></a>
</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="clear bot_space_m">   </div>
<div class="col2-set addresses-list">
    <div class="col-1 addresses-primary">
        <h2><?php echo $this->__('Default Address') ?></h2>
        <ol>
        <?php // if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
            <!--<li class="item">
                <h3><?php echo $this->__('Default Billing Address') ?></h3>
                <address>
                    <?php // echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                </address>
                <p><a href="<?php // echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Billing Address') ?></a></p>
           </li>-->
        <?php // else: ?>
            <!--<li class="item">
                <h3><?php echo $this->__('Default Billing Address') ?></h3>
                <?php echo $this->__('You have no default billing address in your address book.') ?>
            </li>-->
        <?php // endif ?>

        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
            <li class="item">
                <address>
                    <?php /* @var $defaultAddress Mage_Customer_Model_Address */
                        $defaultAddress = Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses);
                        echo $this->getLayout()->createBlock('core/template')
                            ->setAddress($defaultAddress)
                            ->setTemplate('customer/address/template/html.phtml')
                            ->renderView();
                    ?>
                </address>
            </li>
        <?php else: ?>
            <li class="item empty">
                <h3><?php echo $this->__('Default Shipping Address') ?></h3>
                <p><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
            </li>
        <?php endif ?>
        </ol>
        <p><a class="edit_btn" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Edit') ?></a></p>
        <button type="button" title="<?php echo $this->__('Add New Address') ?>" class="button" onclick="window.location='<?php echo $this->getAddAddressUrl() ?>';"><span><span><?php echo $this->__('Add New Address') ?></span></span></button>
    </div>
    <div class="col-2 addresses-additional">
        <h2><?php echo $this->__('Other Addresses') ?></h2>
        <ol>
        <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
            <?php foreach($_pAddsses as $_address): ?>
            <li class="item">
                <address>
                    <?php
                        echo $this->getLayout()
                                  ->createBlock('core/template')
                                  ->setAddress($_address)
                                  ->setTemplate('customer/address/template/html.phtml')
                                  ->renderView();
                    ?>
                </address>
<!--            <div class="email"><span class="content">--><?php //echo $this->htmlEscape($this->getCustomer()->getEmail()) ?><!--</span></div>-->
                <div class="change-default-address"><a href="<?php echo $this->getUrl('customer/address/changeDefaultAddress/',array('id'=>$_address->getId())); ?>"><?php echo $this->__('Change to Default Address')?></a></div>
                <div class="address-links"><a class="edit_btn" href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo $this->helper('gri_customer')->__('Edit') ?></a><a href="#" class="link-remove" onclick="return deleteAddress('<?php echo $_address->getId() ?>');"><?php echo $this->__('Delete') ?></a></div>
            </li>
            <?php endforeach; ?>
        <?php else: ?>
            <li class="item empty">
                <p><?php echo $this->__('You have no additional address entries in your address book.') ?></p>
            </li>
        <?php endif ?>
        </ol>
    </div>
</div>
<!--<div class="buttons-set">
    <p class="back-link"><a href="<?php /*echo $this->escapeUrl($this->getBackUrl()) */?>"><small>&laquo; </small><?php /*echo $this->__('Back') */?></a></p>
</div>-->
<script type="text/javascript">
//<![CDATA[
    function deleteAddress(addressId) {
        if(confirm('<?php echo $this->__('Are you sure you want to delete this address?') ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
        }
        return false;
    }
//]]>
</script>
