<?php
    /* @var $this Gri_CatalogSearch_Block_Top_Search */
    /* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
    $catalogSearchHelper =  $this->helper('gri_catalogsearch/advanced');
?>
<div class="search-content">
<form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
    <div class="form-search">
        <ul class="form-list">
            <li>
                <div class="input-box">
                    <select name="brand" class="selectBox">
                        <?php foreach($this->getBrandOptions() as $brand): ?>
                            <option value="<?php echo $brand['value']; ?>"><?php echo $brand['label'] ?></option>
                        <?php endforeach ;?>
                    </select>
                 </div>
            </li>
            <li>
                <div class="input-box">
                    <select name="category_id" class="selectBox">
                        <option><?php echo $this->__('Select Category') ?></option>
                        <?php foreach($this->getCategoryOptions() as $category): ?>
                            <option value="<?php echo $category->getId(); ?>"><?php echo $category->load(NUll)->getName(); ?></option>
                        <?php endforeach ;?>
                    </select>
                </div>
            </li>
            <?php if(1==0):?>
            <li>
                <div class="input-box">
                    <select name="color_filter_1"  class="selectBox">
                        <?php foreach($this->getColorOptions() as $color): ?>
                            <option value="<?php echo $color['value']; ?>"><?php echo $color['label']; ?></option>
                        <?php endforeach ;?>
                    </select>
                </div>
            </li>
            <?php endif;?>
            <li>
                <div class="input-box">
                    <input type="text" name="name" id="search" onblur="if(this.value==''){this.value='<?php echo $catalogSearchHelper->getEscapedQueryText() ?>';}" onfocus="if(this.value=='<?php echo $catalogSearchHelper->getEscapedQueryText() ?>'){this.value='';}" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" >
                </div>
            </li>
            <li>
                <div class="input-box">
                    <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
                </div>
            </li>
            <input name="column_count" type="hidden" value="<?php  echo Gri_CatalogSearch_Block_Advanced_Result::COULMN_COUNT; ?>" />
          </ul>
          <script type="text/javascript">
              //<![CDATA[
              var searchForm = new Varien.searchForm('search_mini_form', 'search', '');
              
              //]]>
          </script>
    </div>
</form>
</div>


