<?php
/**
* Interakting Slider
*
* NOTICE OF LICENSE
*
* This source file is subject to the Open Software License (OSL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/osl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@magentocommerce.com and you will be sent a copy immediately.
*
* @category   BusinessDecision
* @package    BusinessDecision_Interaktingslider
* @author     Business & Decision Picardie - contactmagento@interakting.com
* @copyright  Copyright (c) 2009 Business & Decision (http://www.businessdecision.com)
* @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
/* @var $this BusinessDecision_Interaktingslider_Block_Interaktingslider */
$slides = $this->getSlides();
if($this->getModel()->isVisible()){
?>
<div id="slides-<?php echo $this->getNameInLayout(); ?>" class="slides">
    <div class="slides_container">
        <?php if (!$this->getModel()->hasSlides()) { ?>
        <div id="no-slide"><?php echo $this->getModel()->getNoSlideText()?></div>
        <?php } ?>
    <?php
    /* @var $slide BusinessDecision_Interaktingslider_Model_Slide */
    foreach (array_values($slides) as $k => $slide) { ?>
        <div class="slide"<?php if ($k) { ?> style="display:none;"<?php } ?>>
            <?php echo $slide->getFormatedContent(); ?>
        </div>
    <?php } ?>
    </div>
</div>
<?php if ($this->getModel()->hasSlides()) {
    echo $this->addJs();
?>
<script type="text/javascript">
    (function($){$(window).load(function(){
        $('#slides-<?php echo $this->getNameInLayout(); ?>').slides({
            preload: false,
            play: <?php echo $this->getDelay() * 1000; ?>,
            slideSpeed: <?php echo $this->getSpeed(); ?>,
            pause: 1000,
            hoverPause: true,
            generateNextPrev: true
        });
    })})(jQuery);
</script>
<?php
    }
}
?>
