<?php /* @var $this Amasty_Rules_Block_Checkout_Discount */ ?>

<tr class="summary-total">
    <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
             <div class="summary-collapse"><?php echo $this->getTotal()->getTitle() ?></div>
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
    </td>
    <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
            <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
    </td>
</tr>

<?php if (is_array($this->getTotal()->getFullInfo())) : ?>
    <?php foreach ($this->getTotal()->getFullInfo() as $info): ?>
        <tr class="summary-details-amrules summary-details">
            <td colspan="<?php echo $this->getColspan(); ?>"><?php echo $info['label']; ?></td>
            <td rowspan="1">-<?php echo $this->helper('checkout')->formatPrice($info['amount']); ?></td>
        </tr>
    <?php endforeach; ?>
<?php endif; ?>
