<?php
/**
USAGE:

Simple:

<?php echo $this->getLayout()->createBlock('customer/widget_name')
   ->setObject($this->getAddress())
   ->toHtml() ?>

For checkout/onepage/shipping.phtml:

<?php echo $this->getLayout()->createBlock('customer/widget_name')
   ->setObject($this->getAddress())
   ->setFieldIdFormat('shipping:%s')
   ->setFieldNameFormat('shipping[%s]')
   ->setFieldParams('onchange="shipping.setSameAsBilling(false);"')
   ->toHtml() ?>
*/
/* @var $this Mage_Customer_Block_Widget_Name */
?>
<!--<?php // if ($this->showPrefix()) { ?>
<div class="name-prefix clearer">
    <label for="<?php echo $this->getFieldId('prefix')?>"<?php if ($this->isPrefixRequired()) echo ' class="required"' ?>><?php if ($this->isPrefixRequired()) echo '' ?><?php echo $this->getStoreLabel('prefix') ?></label>
    <div class="input-box">
        <?php if ($this->getPrefixOptions() === false): ?>
        <input type="text" id="<?php echo $this->getFieldId('prefix')?>" name="<?php echo $this->getFieldName('prefix')?>" value="<?php echo $this->escapeHtml($this->getObject()->getPrefix()) ?>" title="<?php echo $this->getStoreLabel('prefix') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('prefix') ?>" <?php echo $this->getFieldParams() ?> />
        <?php else: ?>
        <?php foreach (array_values($this->getPrefixOptions()) as $k => $_option) if ($_option) { ?>
        <input type="radio" id="<?php echo $id = $this->getFieldId('prefix-' . $k); ?>" name="<?php echo $this->getFieldName('prefix')?>" class="radio" title="<?php echo $_option?>" value="<?php echo $_option?>" />
        <label for="<?php echo $id; ?>"><?php echo $_option?></label>
        <?php } ?>
        <?php endif; ?>
    </div>
</div>
<?php // } ?>-->
<!--<div class="customer-name clearer">-->
    <div class="field name-firstname">
        <div class="input-box">
            <label for="<?php echo $this->getFieldId('firstname')?>" class="required"><?php echo $this->helper('gri_customer')->__('First Name') ?></label>
            <input type="text" id="<?php echo $this->getFieldId('firstname')?>" name="<?php echo $this->getFieldName('firstname')?>" value="<?php echo  $this->escapeHtml($this->getObject()->getFirstname()); ?>" title="<?php echo $this->helper('gri_customer')->__($this->getStoreLabel('firstname')) ?>" maxlength="255" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('firstname') ?>" <?php echo $this->getFieldParams() ?> />
        </div>
    </div>
    <div class="field name-lastname">
        <div class="input-box">
            <label for="<?php echo $this->getFieldId('lastname')?>" class="required"><?php echo $this->__('Last Name') ?></label>
            <input type="text" id="<?php echo $this->getFieldId('lastname')?>" name="<?php echo $this->getFieldName('lastname')?>" value="<?php  echo $this->escapeHtml($this->getObject()->getLastname()); ?>" title="<?php echo $this->getStoreLabel('lastname') ?>" maxlength="255" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('lastname') ?>" <?php echo $this->getFieldParams() ?> />
        </div>
    </div>
<?php if ($this->showMiddlename()): ?>
<?php $isMiddlenameRequired = $this->isMiddlenameRequired(); ?>
    <div class="field name-middlename">
        <div class="input-box">
            <label for="<?php echo $this->getFieldId('middlename')?>"<?php echo $isMiddlenameRequired ? ' class="required"' : '' ?>><?php echo $isMiddlenameRequired ? '' : '' ?><?php echo $this->getStoreLabel('middlename') ?></label>
            <input type="text" id="<?php echo $this->getFieldId('middlename')?>" name="<?php echo $this->getFieldName('middlename')?>" value="<?php echo $this->escapeHtml($this->getObject()->getMiddlename()) ?>" title="<?php echo $this->getStoreLabel('middlename') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('middlename') ?>" <?php echo $this->getFieldParams() ?> />
        </div>
    </div>
<?php endif; ?>
<?php if ($this->showSuffix()): ?>
    <div class="field name-suffix">
        <div class="input-box">
            <label for="<?php echo $this->getFieldId('suffix')?>"<?php if ($this->isSuffixRequired()) echo ' class="required"' ?>><?php if ($this->isSuffixRequired()) echo '' ?><?php echo $this->getStoreLabel('suffix') ?></label>
            <?php if ($this->getSuffixOptions() === false): ?>
            <input type="text" id="<?php echo $this->getFieldId('suffix')?>" name="<?php echo $this->getFieldName('suffix')?>" value="<?php echo $this->escapeHtml($this->getObject()->getSuffix()) ?>" title="<?php echo $this->getStoreLabel('suffix') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('suffix') ?>" <?php echo $this->getFieldParams() ?> />
        <?php else: ?>
            <select id="<?php echo $this->getFieldId('suffix')?>" name="<?php echo $this->getFieldName('suffix')?>" title="<?php echo $this->getStoreLabel('suffix') ?>" class="<?php echo $this->helper('customer/address')->getAttributeValidationClass('suffix') ?>" <?php echo $this->getFieldParams() ?>>
            <?php foreach ($this->getSuffixOptions() as $_option): ?>
                <option value="<?php echo $_option?>"<?php if ($this->getObject()->getSuffix()==$_option):?> selected="selected"<?php endif; ?>><?php echo $this->__($_option)?></option>
            <?php endforeach; ?>
            </select>
        <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
<!--</div>-->
