<?php
/**
 * @see Mage_Adminhtml_Block_Customer_System_Config_Validatevat
 */
?>
<script type="text/javascript">
//<![CDATA[
    function updateOnSaleAttribute() {
        var elem = $('<?php echo $this->getHtmlId() ?>'),
        params = {'sku': $('gri_attribute_on_sale_sku').value};
        new Ajax.Request('<?php echo $this->getAjaxUrl() ?>', {
            parameters: params,
            onSuccess: function(response) {
                result = '<?php echo $this->__('Update Failure') ?>';
                try {
                    response = response.responseText;
                    if (response == 1) {
                        result = '<?php echo $this->__('Update Success') ?>';
                        elem.removeClassName('fail').addClassName('success')
                    } else {
                        elem.removeClassName('success').addClassName('fail')
                    }
                } catch (e) {
                    elem.removeClassName('success').addClassName('fail')
                }
                $('updated_result').update(result);
            }
        });
    }
//]]>
</script>
<button onclick="javascript:updateOnSaleAttribute(); return false;" class="scalable" type="button" id="<?php echo $this->getHtmlId() ?>">
    <span id="updated_result"><?php echo $this->escapeHtml($this->getButtonLabel()) ?></span>
</button>