<?php
/* @var $this Mage_Core_Block_Template */
?>
</td>
</tr>

<tr>
  <td><table align="center" width="560" cellspacing="0" cellpadding="0">
      <tbody>
        <tr>
          <td><table style="width:185px;" cellspacing="0" cellpadding="0">
              <tbody>
                <tr>
                  <td valign="top" align="center"><a style="color:#000;text-decoration: none;font-size:19px;font-family:Arial, Helvetica, sans-serif" target="_blank" href="<?php echo $this->getUrl('customer-service/shipping-delivery'); ?>"><?php echo $this->__('FREE SHIPPING'); ?></a><br /></td>
                </tr>
                <tr>
                  <td align="center" valign="top" style="font-family:Arial, Helvetica, sans-serif;font-size:11px"><?php echo $this->__('Orders over USD$130'); ?></td>
                </tr>
              </tbody>
            </table></td>
          <td><table style="width:201px;border-left:1px solid #D8D8D8;border-right:1px solid #D8D8D8;padding:0 10px;margin:0;" cellspacing="0" cellpadding="0">
              <tbody>
                <tr>
                  <td valign="top" align="center"><a style="color:#000;text-decoration: none;font-size:19px;font-family:Arial, Helvetica, sans-serif" target="_blank" href="<?php echo $this->getUrl('customer-service/how-to-shop'); ?>"><?php echo $this->__('SHOPPING GUIDE'); ?></a><br /></td>
                </tr>
                <tr>
                  <td valign="top" align="center" style="font-family:Arial, Helvetica, sans-serif;font-size:11px"><?php echo $this->__('Shop now'); ?></td>
                </tr>
              </tbody>
            </table></td>
          <td><table style="width:173px;" cellspacing="0" cellpadding="0">
              <tbody>
                <tr>
                  <td valign="top" align="center"><a style="color:#000;text-decoration: none;font-size:19px;font-family:Arial, Helvetica, sans-serif" target="_blank" href="<?php echo $this->getUrl('vip'); ?>"><?php echo $this->__('BECOME OUR VIP'); ?></a><br /></td>
                </tr>
                <tr>
                  <td valign="top" align="center" style="font-family:Arial, Helvetica, sans-serif;font-size:11px"><?php echo $this->__('15% discount all year round'); ?></td>
                </tr>
              </tbody>
            </table></td>
        </tr>
      </tbody>
    </table>
    <br />
    <br />
<tr>
  <td valign="top" colspan="3" style="text-align:left;padding:20px 35px;font-size:11px;color:#666;line-height:14px;margin:0;font-family:Arial, Helvetica, sans-serif"><?php echo $this->__('# Please do not reply to this email. For any enquiry or concern, please email us at <a href="%s">%s</a>', Mage::getStoreConfig('trans_email/ident_support/email'), Mage::getStoreConfig('trans_email/ident_support/email')); ?><br />
    <br />
    &copy; 2013 <a style="color:#666;text-decoration: none;" href="<?php echo $this->getUrl('/'); ?>">www.CENTRALCENTRALSHOP.com</a> <?php echo $this->__('All rights reserved'); ?></td>
</tr>
  </tbody>
  </table>
  </td>
  </tr>
  <tr>
  <td style="width:650px;height:1px;" bgcolor="#000000" align="center" valign="top">&nbsp;</td>
</tr>
  </tbody>
  </table>
  </td>
  <td width="24" valign="top" bgcolor="#000000">&nbsp;</td>
  </tr>
  </tbody>
  </table>
