<?php /* @var $this Mage_Customer_Block_Account_Dashboard_Address */ ?>
<?php /* @var $_directoryHelper Gri_Directory_Helper_Data */
    $_directoryHelper = Mage::helper('gri_directory');
    $internalCode = $_directoryHelper->getInternalCode();
?>
<div class="col2-set my-address">
    <div class="box">
        <div class="box-title">
            <h3><?php echo $this->__('Address Book') ?></h3>
        </div>
        <div class="box-content">
            <div class="col-1">
                <address>
                    <?php //echo $this->getPrimaryShippingAddressHtml() ?>
                    <?php $_address = $this->getCustomer()->getPrimaryShippingAddress();
                        if ( $_address instanceof Varien_Object ) {
                            echo $this->getLayout()->createBlock('core/template')
                                              ->setAddress($_address)
                                              ->setTemplate('customer/address/template/html.phtml')
                                              ->renderView();
                            } else {
                                echo Mage::helper('customer')->__('You have not set a default shipping address.');
                            }
                        ?>
                </address>
                <div class="clear"></div>
            </div>
            <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit') ?></a>
        </div>
    </div>
</div>
